grafana/synthetic-monitoring-app

- src/validation.ts
> Fix check validations

- src/components/CheckEditor.tsx
- src/validation.ts
> Validate that HTTP target is a valid URL

- package.json
- src/validation.test.ts
- src/validation.ts
- yarn.lock
Add validations for the targets of PING, DNS and TCP checks. Make sure
we are getting something that is either a valid IP address or a valid
hostname. The API will also perform this validation, possibly more
strictly, so this is only meant to give the user some immediate
feedback.
> Validate PING, DNS and TCP targets

- src/validation.test.ts
> Fix linter errors in validation.test.ts

- jest.config.js
- package.json
- src/components/DnsSettings.test.tsx
- src/components/DnsSettings.tsx
- src/components/ListInput.tsx
- yarn.lock
I notice that the DNS validation fields were tilting a bit, and thought that might be a nice first PR. I also took the opportunity to refactor that component a bit and set up some tests using react testing library. This PR is very much just trying things out and getting familiar with the tooling, any and all feedback very welcome!.
Before:
After:
> Dns settings refactor

- .circleci/config.yml
Adds the "report" step back into our circle ci config
> Build config

- jest.config.js
- src/components/TenantAPISetupForm.test.tsx
- src/components/TenantAPISetupForm.tsx
- src/components/TenantSetup.tsx
- src/components/constants.ts
fixes https://github.com/grafana/synthetic-monitoring-app/issues/15
- Abstracts the tenant api setup step into it's own form
- Shows all types of errors returned from the setup api call (previously just the backend errors were showing up)
- Adds some tests for the tenant api setup form
> Api config error handling

- src/hooks/useMetricData.ts
Closes https://github.com/grafana/synthetic-monitoring-app/issues/87
Refetches metric data every 60 seconds.
> feat: refresh metric data on an interval

- .release-it.js
- src/components/CheckEditor/CheckEditor.tsx
- src/components/ProbeEditor.test.tsx
- src/components/ProbeEditor.tsx
- src/types.ts
> fix: give feedback when probe creation or updating fails

- src/validation.test.ts
- src/validation.ts
> Target validations

- src/components/CheckEditor/CheckEditor.test.tsx
- src/components/http/HttpSettings.tsx
> fix: fix http follow redirect setting being unresponsive

- .circleci/config.yml
- scripts/staging-install.sh
This will automatically deploy the latest github release to a testing environment. It has a gate to promote the release to production with manual approval in CircleCi
> Staging install

- src/components/CheckEditor/ProbeOptions.tsx
- src/components/SliderInput.tsx
> fix: specify a step size for slider input

- .release-it.js
- src/components/CheckEditor/CheckEditor.test.tsx
- src/components/CheckEditor/CheckEditor.tsx
- src/components/HorizonalCheckboxField.tsx
- src/components/TLSConfig.tsx
- src/components/http/HttpSettings.tsx
- src/plugin.json
> Switches to checkboxes

- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-summary.json
> chore: update dashboard version numbers

- .circleci/config.yml
- src/components/CheckEditor/checkFormTransformations.ts
- src/components/http/HttpSettings.tsx
> fix: handle http regex validation value deletion bug

- src/components/CheckList.tsx
Fixes issue #164 
The pagination component was in use but the check list wasn't actually paginating the results.
> Paginate checks

- README.md
> docs: update provisioning flow, remove api key flow

- src/page/WelcomePage.tsx
This handles an additional error case with the setup request on the welcome page
> fix: handle error response on welcome page

- src/components/TenantView/LinkedDatasourceView.tsx
> chore: remove datasource edit button

- PULL_REQUEST_TEMPLATE
Borrowed and adapted from Grafana's pull request template
> chore: add pull request template

- src/components/Alerting.tsx
- src/components/InstanceProvider.tsx
> Gate alerts by admin role

- src/plugin.json
> fix: remove broken config link

- src/components/CheckEditor/CheckProbes.tsx
> fix: prevent clearing probes from clearing the whole form

- src/components/CheckEditor/checkFormTransformations.ts
> fix: handle tls config with undefined cert

- src/components/CheckListItem/CheckItemActionButtons.tsx
- src/components/CheckListItem/CheckListItem.tsx
- src/validation.ts
Fixes #75 
In addition to increasing the job name limit, this PR adds some text truncation and a view dashboard button in the list view.
> fix: increase job name length limit

- src/components/LabelFilterInput.tsx
> fix: deduplicate label filter values

- src/components/AlertLabels.tsx
- src/components/CheckEditor/CheckEditor.tsx
- src/components/LabelField.tsx
- src/validation.test.ts
- src/validation.ts
> fix: validate that labels names are not duplicated

- src/components/constants.ts
- src/validation.test.ts
- src/validation.ts
> fix: allow curly brackets in http url params

- .circleci/config.yml
- PULL_REQUEST_TEMPLATE
> chore: change references from `master` to `main`

- README.md
> Fix: Update provisioning instructions in README.md

- CODEOWNERS
- CODE_OF_CONDUCT.md
CODE_OF_CONDUCT is copied from Grafana's, and CODEOWNERS is the same as
the agent's.
Fixes #
> Chore: add CODE_OF_CONDUCT and CODEOWNERS

- .github/dependabot.yml
> Chore: Add dependabot configuration file

- .gitignore
- CONTRIBUTING.md
- scripts/custom.ini
- scripts/local-provisioning/datasources/.gitignore
- scripts/local-provisioning/datasources/example.yaml
- scripts/local-provisioning/plugins/.gitignore
- scripts/local-provisioning/plugins/example.yaml
- scripts/run-local.sh
Provides a script and some configuration to run grafana with provisioning in a docker container
> Local docker

- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-tcp.json
> feat: format dashboard log panel to include the probe name

- CONTRIBUTING.md
- src/components/CheckListItem/CheckListItem.tsx
- src/components/CheckListItem/CheckListItemDetails.tsx
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/321
**Before:**
**After:**
for multiple locations:
for single location:
for disabled check:
> feat(ui): add locations count in checks list

- src/components/CheckEditor/CheckEditor.tsx
- src/components/CheckEditor/checkFormTransformations.ts
- src/components/CheckUsage.tsx
- src/components/HorizonalCheckboxField.tsx
- src/types.ts
Fixes usage calculation when creating a check and selecting "Publish advanced metrics". Also renamed form field to better reflect the value.
> fix: checking show advanced metrics updates usage calculation

- scripts/run-local.sh
The run local script should pull the latest container if it's about to run the latest container
> chore: pull latest container

- package.json
- src/components/Clipboard/Clipboard.tsx
- src/components/Clipboard/CopyToClipboard.tsx
- src/components/Clipboard/index.ts
- src/components/ProbeEditor.tsx
- yarn.lock
Fixes #326 
This fixes a layout issue with the token on probe creation, and adds a "copy to clipboard" button. I lifted the copy to clipboard from the onboarding plugin.
Before:
After:
> Wrap probe token

- jest.config.js
- src/test/setupTests.ts
> chore: silence inline svg errors

- src/components/ProbeEditor.tsx
- src/components/ProbeStatus.tsx
> fix: remove unused public control from probes page

- __mocks__/@grafana/ui.tsx
- src/components/CheckList/CheckList.test.tsx
- src/components/CheckList/CheckList.tsx
- src/components/CheckList/checkFilters.ts
- src/components/CheckList/index.ts
- src/page/ChecksPage.tsx
- adds a select to CheckList to filter by probes, with AND operator
- namespace CheckList with test file and some helpers
> Filter checks by probe

- src/analytics.ts
- src/components/CheckList/CheckList.test.tsx
- src/components/Thresholds/ThresholdFormSection.tsx
- src/components/Thresholds/ThresholdGlobalSettings.test.tsx
Next phase of the test output cleanup: fixing act warnings and analytics logs
> chore: fix tests throwing act warnings

- README.md
While trying to include this plugin in an on prem setup I struggled to understand where I could find the values required in the plugin configuration and faced several API errors simply due to mis-configuration. After browsing the code I finally ended up on the contributing guidelines where it was better explained.
This PR should make it more understandable for future users where to find the values expected in the plugin provisioning configuration file. It simply copies over the information from the contribution guideline to the README with minor adjustments.
Fixes #
> docs: add details to expected plugin configuration values

- src/components/InstanceSelection.tsx
> fix: disable setup button if required instances arent selected

- CHANGELOG.md
- package.json
- src/components/InstanceProvider.tsx
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/273
> feat: [cr] gracefully handle error connecting to API

- .gitignore
- package.json
- src/components/CheckList/CheckList.test.tsx
- src/components/CheckList/CheckList.tsx
- src/components/CheckListItem/CheckItemActionButtons.tsx
- src/components/CheckListItem/CheckListItem.tsx
- src/components/CheckListItem/CheckTypePill.tsx
- src/components/LabelFilterInput.tsx
- src/utils.ts
- yarn.lock
Contains a number of small changes to improve accessibility. Next steps: make a script to test all pages, will work nicely with new React Router
> chore: [cr] install pa11y and make accessibility changes to checks list

- src/components/LabelField.tsx
This matches the API and the agent.
Fixes #
> feat: increase user label limit to 10

- src/components/Alerting.test.tsx
- src/components/alertingTransformations.ts
- src/components/constants.ts
- src/hooks/useAlerts.ts
- src/types.ts
> chore: groundwork to add more alerts

- src/page/WelcomePage.tsx
Closes https://github.com/grafana/synthetic-monitoring-app/issues/176
> chore: add a loading indicator to the welcome page

- src/components/AccessToken.tsx
This PR allows to open the linked document in a new window or tab. I added also the style class `highlight-word` to be consistency with other linked documents.
Fixes #430
That's my first contribution on a open source project :tada:, please let me know if I've missed out anything.  
Screenshot:
> fix: linked document link is relative fix

- src/components/DashboardUpdateModal.tsx
- src/components/Routing.tsx
- src/dashboards/sm-summary.json
- src/hooks/useNavigation.ts
Fixes #432 
~I'm not really sure why, but react-router won't pick up the route change unless the browser refreshes. I feel like I've missed something here.~
Should be good to go
> fix: handle dashboard redirects

- src/components/DashboardUpdateModal.tsx
- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-summary.json
- src/dashboards/sm-tcp.json
- src/dashboards/sm-traceroute.json
Fixes #447 
Also revs the dashboard versions so changes from #446 get applied
> fix: only show dashboard update modal to admin users

- .circleci/config.yml
- package.json
- scripts/lint-dashboards.sh
- src/dashboards/.lint
Adopt https://github.com/grafana/dashboard-linter to lint SM dashboards. 
This will prevent us from shipping a broken dashboard 
Fixes #
- checkout https://github.com/grafana/dashboard-linter
- Excluded two lint rules because they don't apply to SM Dashboards
> chore: lint dashboards using dashboard-linter

- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-summary.json
- src/dashboards/sm-tcp.json
- src/dashboards/sm-traceroute.json
Removed old deprecated metrics from dashboards.
Fixes #401
> chore: remove deprecated metrics OR queries from dashboards

- scripts/custom.ini
- src/components/Alerting.tsx
- src/hooks/useAlerts.ts
- src/hooks/useUnifiedAlertsEnabled.ts
> fix: check config for unified alerting enablement

- src/components/ProbeEditor/ProbeEditor.tsx
> fix: show a more useful error on probe delete failure

- scripts/custom.ini
- src/hooks/useAlerts.ts
- src/hooks/useGrafanaVersion.ts
> fix: handle a breaking change in the alerting api for grafana v9

- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-summary.json
- src/dashboards/sm-tcp.json
Tweak the current expression to avoid situations where a 1 is becoming a
2 because of rounding. Also tweak the expression to make it a little
simpler.
Fixes #
> fix: change the way we compute uptime to avoid going over 100%

- CHANGELOG.md
- src/components/SuccessRateContextProvider.tsx
> fix: ensure 100 doesn't render as 100.0

- package.json
- src/plugin.json
> chore: update worldmap panel dependency to 0.3.3

- src/components/CheckEditor/CheckEditor.tsx
- src/components/CheckList/CheckList.tsx
- src/components/InstanceProvider.tsx
- src/components/ProbeList.tsx
- src/components/Routing.tsx
- src/components/UnprovisionedSetup.tsx
- src/page/CheckRouter.tsx
- src/plugin.json
- src/types.ts
based on https://github.com/grafana/synthetic-monitoring-app/pull/479
* Fixes some instances of flashing empty page with loading spinner (more of those to fix)
* Removes empty div wrapping Switch (caused issues for Page height) 
* Fixes some double headings (maybe there is a cleaner way to reduce duplication of those)
* Fixes max heigh 100% on HorizontalGroup causing all the card items to be pushed outside page  (new issue with HorizontalGroup when a direct child of PluginPage, the height 100% is now actually having an affect)
> More topnav fixes

- CHANGELOG.md
- package.json
> chore: bump to version 1.9.27

- src/components/AlertRuleForm.tsx
- src/components/Alerting.tsx
- src/components/CheckEditor/CheckEditor.tsx
**What this PR does / why we need it**: 
Customer noticed that the Alerts tab has text & links that refer to the old Grafana Cloud Alerting plugin, which has been deprecated & removed from HG instances when they upgrade to v9. This fixes that and points them to the corresponding 
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/469
> Fix: Update Alert URL

- CHANGELOG.md
- package.json
> Chore: Bump to v1.9.28

- package.json
- scripts/custom.ini
- src/components/CheckEditor/CheckEditor.tsx
- src/components/CheckTestResult.tsx
- src/components/CheckTestResultsModal.tsx
- src/components/Collapse.tsx
- src/datasource/DataSource.ts
- src/hooks/useLogData.ts
- src/types.ts
- src/utils.ts
Add a way to test checks before submitting. Currently behind a feature flag
> Ad hoc checks

- src/components/CheckEditor/CheckEditor.tsx
- src/components/CheckTestResultsModal.tsx
> chore: add a loading state for check tests and a timeout handler

- PULL_REQUEST_TEMPLATE
- cspell.config.json
- dummy.scss
- package.json
- src/components/CheckEditor/CheckEditorExisting.test.tsx
- src/components/CheckEditor/checkFormTransformations.ts
- src/components/CheckEditor/testConstants.ts
- src/components/TerraformConfig/terraformConfigUtils.ts
- src/components/TerraformConfig/terraformTypes.ts
- src/components/http/HttpSettings.tsx
- src/types.ts
- yarn.lock
> feat: add support for proxy connect headers

- src/page/WelcomePage.tsx
> fix: center align welcome page and allow it to cover arbitrary widths

- src/components/CheckTestResultsModal.tsx
- src/datasource/DataSource.ts
- src/utils.test.ts
- src/utils.ts
> fix: check test runs should be limited to 5 probes

- src/components/CheckEditor/checkFormTransformations.ts
- src/components/CheckEditor/testConstants.ts
- src/components/MultiHttp/AvailableVariables.tsx
- src/components/MultiHttp/MultiHttpSettingsForm.test.tsx
- src/components/MultiHttp/MultiHttpTypes.ts
- src/components/MultiHttp/Tabs/TabSection.tsx
- src/components/MultiHttp/Tabs/Tabs.tsx
- src/components/constants.ts
- src/types.ts
Add the ability to pipe a variable from one request to the next
> Multi http variables

- src/hooks/useAlerts.ts
> fix: suppress expected alert group fetching error toast

- package.json
Update to v1.11.2
Closes #554 #555
> bump: update version to 1.11.2

- src/scenes/Common/editButton.tsx
- src/scenes/Common/variables.ts
- src/scenes/DNS/dnsScene.ts
- src/scenes/HTTP/httpScene.ts
- src/scenes/MULTIHTTP/multiHttpScene.ts
- src/scenes/PING/pingScene.ts
- src/scenes/TCP/getTcpScene.ts
- src/scenes/Traceroute/getTracerouteScene.ts
> feat: add an edit button to the scenes

- .github/workflows/is-compatible.yml
Taken from default workflow added by `create-plugin`.
Fixes #
> Add Grafana API compatibility check workflow

- src/components/MultiHttp/MultiHttpSettingsForm.tsx
> chore: add alerting levels to multihttp form

- src/components/CheckFilters.tsx
- src/components/CheckList/CheckFilterGroup.tsx
- src/components/CheckList/CheckList.test.tsx
- src/components/CheckList/CheckList.tsx
- src/components/CheckList/CheckListScene.tsx
- src/components/CheckList/checkFilters.ts
- src/types.ts
Adds filtering to the visualization list view
Deals with the most pressing parts of #588
> Filters in scenes

- src/plugin.json
> chore: add a description to the plugin info

- src/components/MultiHttp/MultiHttpNew.test.tsx
- src/components/MultiHttp/MultiHttpSettingsForm.test.tsx
- src/components/MultiHttp/Tabs/AssertionsTab.tsx
- src/components/MultiHttp/Tabs/Tabs.tsx
Add some descriptions and more helpful placeholders for assertions
> Clarify assertions

- src/components/CheckListItem/CheckListItem.tsx
- src/components/LatencyGauge.tsx
Adjusts the check list latency gauge so that it uses a multihttp appropriate metric
> Multihttp latency fix

- package.json
- src/scenes/Common/variables.ts
- src/scenes/Summary/errorPctTimeseries.ts
- src/scenes/Summary/errorRateMap.ts
- src/scenes/Summary/latencyTimeseries.ts
- src/scenes/Summary/summaryScene.ts
- src/scenes/Summary/summaryTable.ts
- yarn.lock
This does a couple things to improve the summary:
Instead of listing the checks by type and repeating the charts, it groups everything together. It also makes the view filterable by check type and adds an adhoc filter that allows filtering by the custom labels
> Summary rework

- package.json
- src/components/Table/Table.tsx
- src/components/Table/index.ts
- src/components/Table/tableTheme.ts
- src/scenes/MULTIHTTP/assertionTable.ts
- src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
- src/scenes/SCRIPTED/AssertionsTable/AssertionsTableRow.tsx
- src/scenes/SCRIPTED/AssertionsTable/errorLogs.ts
- src/scenes/SCRIPTED/AssertionsTable/index.ts
- src/scenes/SCRIPTED/AssertionsTable/successOverTimeByProbe.ts
- src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
- src/scenes/SCRIPTED/ResultsByTargetTable/ResultsByTargetTableRow.tsx
- src/scenes/SCRIPTED/ResultsByTargetTable/durationByTargetProbe.ts
- src/scenes/SCRIPTED/ResultsByTargetTable/latencyByPhaseTarget.ts
- src/scenes/SCRIPTED/ResultsByTargetTable/successRateByTargetProbe.ts
- src/scenes/SCRIPTED/getTablePanelStyles.ts
- src/scenes/SCRIPTED/scriptedScene.ts
- yarn.lock
Makes a number of changes to update the scripted dashboard. This could also be ported to the multihttp dashboard
> Scripted check scene rev2

- src/components/K6CheckCodeEditor.test.tsx
- src/components/K6CheckCodeEditor.tsx
> chore: add an explanation tooltip for why we need an instance input

- src/components/CheckTestButton.tsx
- src/components/K6CheckCodeEditor.tsx
- src/components/constants.ts
- src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
- src/scenes/SCRIPTED/AssertionsTable/successOverTimeByProbe.ts
- src/validation.ts
This fixes a number of issues we got as feedback:
- Frequency in the check list is now correct
- Links to k6 checks/assertions docs updated to the correct URL
- Make the default script more useful (add an assertion, use test.k6.io instead of grafana.com, add a console.log)
- Fixed a bug with timeout validations
- Fixed a bug with validations for job/instance not rendering error messages in the UI
- Put submission errors down by the submit button where they are visible
- Max value of success rate by probe location chart in the dashboard set to 100%
> fix: a number of minor UX papercuts related to validations, layout, etc

- src/scenes/Summary/errorPctTimeseries.ts
- src/scenes/Summary/errorRateMap.ts
- src/scenes/Summary/latencyTimeseries.ts
- src/scenes/Summary/summaryScene.ts
- src/scenes/Summary/summaryTable.ts
> fix: add a probe filter to the summary dashboard

- package.json
- src/scenes/Common/alertAnnotations.ts
- src/scenes/Common/variables.ts
- src/scenes/DNS/dnsScene.ts
- src/scenes/HTTP/errorRateTimeseries.ts
- src/scenes/HTTP/httpScene.ts
- src/scenes/HTTP/latencyByPhase.ts
- src/scenes/PING/pingScene.ts
- src/scenes/SCRIPTED/probeDuration.ts
- src/scenes/SCRIPTED/scriptedScene.ts
- src/scenes/Summary/summaryScene.ts
- src/scenes/TCP/getTcpScene.ts
- src/scenes/Traceroute/getTracerouteScene.ts
- src/scenes/Traceroute/routeHash.ts
> feat: add alert annotations to all the dashboards

- src/components/NameValueInput/NameValueInput.tsx
- src/components/http/HttpSettings.tsx
- src/utils.types.ts
Allow unlimited headers in http requests
> Allow unlimited headers

- .drone.yml
- Makefile
- package.json
- scripts/github-release.js
- yarn.lock
This is just so I can test promoting to gcom without running the full deployment flow
> chore: add a publish to gcom promotion step

- CHANGELOG.md
- src/dashboards/sm-dns.json
- src/dashboards/sm-http.json
- src/dashboards/sm-ping.json
- src/dashboards/sm-summary.json
- src/dashboards/sm-tcp.json
- src/dashboards/sm-traceroute.json
This is a deprecated graph type that depends on angular
> fix: remove graph type from dashboards

- src/components/Gauges/SuccessRateGaugeCheckReachability.tsx
- src/components/Gauges/SuccessRateGaugeCheckUptime.tsx
Uptime and reachability got mixed up at some point
> fix: success rate name switch

- src/components/CheckForm/CheckForm.tsx
- src/components/CheckForm/FormLayouts/CheckDNSLayout.tsx
- src/components/CheckForm/FormLayouts/CheckHttpLayout.tsx
- src/components/CheckForm/FormLayouts/CheckMultiHttpLayout.tsx
- src/components/CheckForm/FormLayouts/CheckPingLayout.tsx
- src/components/CheckForm/FormLayouts/CheckScriptedLayout.tsx
- src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
- src/components/CheckForm/FormLayouts/CheckTracerouteLayout.tsx
- src/components/CheckFormAlert.tsx
- src/components/Collapse.tsx
- src/components/ProbeList/ProbeList.tsx
This is the fourth branch of the feature chain.
Feature branch chain:
[PR 1](https://github.com/grafana/synthetic-monitoring-app/pull/722)
[PR 2](https://github.com/grafana/synthetic-monitoring-app/pull/723)
[PR 3](https://github.com/grafana/synthetic-monitoring-app/pull/724)
_PR 4 - This one_
> Refactor: make smaller more manageable components for check form (feature chain branch: 4 of 4)

- src/components/Routing.test.tsx
- src/components/Routing.tsx
- src/components/SceneRedirecter.tsx
- src/page/DashboardPage.tsx
- src/page/HomePage.test.tsx
- src/page/__mocks__/DashboardPage.tsx
- src/page/__mocks__/SceneHomepage.tsx
- src/test/mocks/@grafana/runtime.tsx
> Redirect old scenes urls

- .drone.yml
- scripts/publish-gcom.sh
> Publish to gcom again

- src/components/constants.ts
**What this PR does / why we need it**: small PR to make sure descriptions are consistent, and update "k6" to lowercase.
Fixes #
> chore: k6 lowercase, make descriptions consistent

- src/components/CheckEditor/CheckEditorExisting.test.tsx
- src/components/CheckEditor/testHelpers.ts
- src/components/CheckForm/CheckForm.tsx
- src/components/CheckForm/FormLayout/FormLayout.test.tsx
- src/components/CheckForm/FormLayout/FormLayout.tsx
- src/components/CheckForm/FormLayout/FormSidebar.tsx
- src/components/CheckForm/FormLayouts/CheckDNSLayout.tsx
- src/components/CheckForm/FormLayouts/CheckHttpLayout.tsx
- src/components/CheckForm/FormLayouts/CheckMultiHttpLayout.tsx
- src/components/CheckForm/FormLayouts/CheckPingLayout.tsx
- src/components/CheckForm/FormLayouts/CheckScriptedLayout.tsx
- src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
- src/components/CheckForm/FormLayouts/CheckTracerouteLayout.tsx
- src/components/CheckForm/MultiHttpNew.test.tsx
- src/components/CheckUsage.tsx
- src/types.ts
Initial exploration for turning the form into a wizard. There's a couple dicey things I chucked in here that I'll highlight in comments to get opinions
> Form as wizard

- package.json
Bump version manually for next release.
> chore: bump version to 1.14.6

- .drone.yml
Updating CI to ping @VikaCep instead of me
> chore: update who gets pinged for deployment PRs

- src/scenes/Common/sslExpiryStat.ts
> Update ssl expiry tooltip

- CHANGELOG.md
> docs: update changelog for 1.14.6

- package.json
> chore: bump version to 1.14.7

- CHANGELOG.md
Updated changelog for  deploying release 1.14.7.
> docs: updated changelog for 1.14.7

- CHANGELOG.md
Updated changelog for deploying release 1.14.8
> docs: update changelog for 1.14.8

- package.json
> chore: bump vesion to 1.14.9

- CHANGELOG.md
Updated changelog for deploying release 1.14.9
> docs: update changelog for 1.14.9

- package.json
> chore: bump version to 1.14.10

- CHANGELOG.md
Updated changelog for deploying release  1.14.10
> chore: update changelog for 1.14.10

- package.json
> chore: bump version to 1.14.11

- CHANGELOG.md
- The check creation pages have been redesigned to be more user-friendly and intuitive. Every check now has five sections regardless of type.
- Check types now have a parent group: Api Endpoint, Multi step and Scripted in the plugin UI.
- Added restrictions when users have the viewer role.
> Release: 1.14.11

- package.json
> docs: update version to 1.14.12

- CHANGELOG.md
Updated the changelog for 1.14.12 and correct date.
> docs: update changelog for 1.14.12

- package.json
Updated `package.json` to version 1.14.13.
> docs: updated to  version 1.14.13

- src/page/AlertingPage.tsx
Just fixing a user-facing typo
> chore: fix typo in alerts error message

- CHANGELOG.md
Updated changelog for deploying release 1.15.0
> docs: update changelog for 1.15.0

- CHANGELOG.md
- package.json
Updated changelog for deploying release 1.15.1
> docs: update changelog number

- package.json
> docs: updated to version 1.15.2

- CHANGELOG.md
Updated changelog for deploying release 1.15.2
> chore: update changelog for 1.15.2

- .drone.yml
- scripts/drone-sign.sh
Updates the Drone file signature after changes made to the release pipeline.
> chore: Update Drone signature

- src/schemas/general/HostNameTarget.ts
- src/validation.test.ts
- src/validation.ts
To make the validation error more in line with what it actually validates.
After
Resolves: https://github.com/grafana/synthetic-monitoring-app/issues/767
Fixed some code style issues while I was in the `validation.ts` file
> fix: check target tooptip

- CHANGELOG.md
Fixes the changelog format and reorders some misplaced entries.
Closes #988.
> fix: Changelog format

- CHANGELOG.md
Add missing feature work in latest release (1.16.8)
> Fix: update changelog with missing comment for last release

- src/page/CheckList/components/CheckCardLabel.tsx
- src/page/CheckList/components/CheckListItemCard.tsx
- src/page/CheckList/components/CheckListItemRow.tsx
Removes "card" border and fixes the `Tag` height on the Checks page.
> Chore: update checks UI styling

- src/components/CheckForm/CheckForm.tsx
- src/components/CheckForm/checkForm.hooks.ts
https://github.com/grafana/synthetic-monitoring-app/pull/1037
Fix the actual original bug that the above PR was meant to solve ☝️ 🤦
> fix: keep reference of submitting form internally

- src/page/CheckList/CheckList.test.tsx
Fixing broken checklist test to unblock deployments.
> fix: fix broken checklist test

- src/configPage/PluginConfigPage/PluginConfigPage.tsx
- src/plugin.json
This PR make the app plugin auto enabled.
This is required to make the plugins not allow users to disable plugins from the catalog.
This is part of grafana/grafana-community-team#318
> chore: make plugin auto enabled

- package.json
- src/components/App.tsx
- src/components/DevTools/DevTools.constants.ts
- src/components/DevTools/DevTools.tsx
- src/components/DevTools/index.ts
- src/hooks/useConfirmBeforeUnload.ts
- yarn.lock
**What this PR does / why we need it**: We need it to resolve #1088 
**Which issue(s) this PR fixes**: 
Fixes #1088 
How to use it: use konami code to enable dev tools modal `↑ ↑ ↓ ↓ ← → ← → b a`
> feat: add dev tools

- src/datasource/plugin.json
Put requests were being blocked.
Explicitly allow them in the `datasource/plugin.json` to enable alerts-per-check feature.
> fix: add put allowed in datasource/plugin.json

- src/hooks/useMonthlyTotalExecutionCount.test.ts
- src/hooks/useMonthlyTotalExecutionCount.ts
Closes https://github.com/grafana/support-escalations/issues/15913
Fixed the calculation of monthly execution counts by removing an unnecessary conversion of frequency from milliseconds to seconds.
The `getTotalChecksPerMonth` function was being called with a frequency value that was incorrectly converted from milliseconds to seconds. This was causing the monthly execution count to be calculated incorrectly. This was a regression due to a recent [change](https://github.com/grafana/synthetic-monitoring-app/commit/40e84e2d66c67135acb07cc1d433181d3e84ca9a#diff-72f9ee34abb365e308826162ae36d7d6cac2469fa7ba0bad7f4dae6e7a2045c6R34) in said function.
- Updated the `useMonthlyTotalExecutionCount` hook to pass the frequency directly without conversion
- Removed the `FREQUENCY_SECONDS` constant in …
> fix: calculation to monthly usage

- src/components/CheckForm/checkForm.hooks.ts
- src/data/useChecks.ts
Comments inline for reasoning.
> fix: correct tracking for update / create check events

- src/components/CheckEditor/FormComponents/DNSRequest.tsx
> fix: typo in DNS form mentioning ICMP

- .policy.yml
> fix: update policybot configuration

- .github/workflows/call_deploy-plugin.yml
- .github/workflows/call_update-deployment-tools.yml
- .github/workflows/dispatch_deploy-plugin.yml
Update GH action names to make the dispatch clearer.
> fix: updated gh action names

- src/components/RunbookRedirectAlert.tsx
- src/components/SceneRedirecter.test.tsx
- src/components/SceneRedirecter.tsx
- src/types.ts
Just a suggestion for the redirect UI for the runbooks. I was playing with some options when I was reviewing the PR and ended up with something that I thought offered a bit more context to the user, so something to consider!
https://github.com/user-attachments/assets/272ddccc-e596-40ca-94d5-b9406bcd748e
> feat: more featured redirect modal UI

- .github/workflows.md
- .github/workflows/call_deploy-plugin.yml
- package.json
- scripts/deployment/create-staging-deployment-pr.sh
Ref https://github.com/grafana/synthetic-monitoring-app/issues/1219
Publish sm-app versions to the [ops](https://grafana-ops.com/grafana/plugins/grafana-synthetic-monitoring-app/) catalog using the shared `grafana/plugin-ci-workflows/actions/plugins/publish/publish` github action.
In order to change OPS `deployment_tools` to read from the catalog, we need to update the `_catalog_version` in `ksonnet/environments/hosted-grafana/waves/provisioned-plugins/grafana-synthetic-monitoring-app/staging.libsonnet` when creating the deployment_tools PR. See https://github.com/grafana/deployment_tools/pull/324425/files#diff-dfc9fa1c993e7d19e1af666238c6c6f454d011661ae951fa524fdfba75f2388cR3
The publishing action is equivalent to the `dev` one, but for the `ops` env: …
> chore: publish to ops catalog

- src/data/permissions.ts
- src/test/utils.ts
- src/types.ts
RBAC for SM has been GA for a while now so the feature flag should be removed.
> chore: remove rbac feature flag

- src/components/OverLimitAlert/OverLimitAlert.test.tsx
- src/components/ProbeCard/ProbeDisabledCapabilities.tsx
- src/components/ProbeEditor/ProbeEditor.test.tsx
- src/components/ProbeEditor/ProbeEditor.tsx
- src/hooks/useCheckTypeGroupOptions.tsx
- src/hooks/useCheckTypeOptions.ts
- src/hooks/useLimits.ts
- src/page/ChooseCheckGroup/ChooseCheckGroup.test.tsx
- src/page/NewProbe/NewProbe.test.tsx
- src/types.ts
Browser checks have been GA for a while now so the feature flag should be removed.
Remove the feature flag for browser checks so they are active by default.
> chore: remove browser feature flag
