grafana/synthetic-monitoring-app

src/dashboards/sm-dns.json

This PR:
grafana/synthetic-monitoring-agent#54
uses an updated version of blackbox_exporter that exposes a metric
called "probe_dns_duration_seconds", which is the time it takes for DNS
check to complete from connection to getting back the RR from the DNS
server. The metric has a label "phase" with three different values for
each phase of the query, just like probe_http_duration_seconds.

Use probe_dns_duration_seconds

---

src/dashboards/sm-summary.json

https://github.com/grafana/grafana/issues/26559 prevents input
placeholders from working correctly when other variables are in the same
field.  This works around the issue by placing the DS_SM_LOGS value into
a "constant" hidden template variable.  This hidden variable is then
used in the link url

fix logs link in summary dashboard

---

.commitlintrc.js
package.json
yarn.lock

This will enforce using the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) message. Down the road we can use the commit message to automate our version bumping and generate changelogs

chore: enforce conventional commits

---

src/dashboards/sm-dns.json

I missed a closing parenthesis in the last commit to this file. Fix
that.
Fixes #59

fix: add missing closing to parenthesis to query

---

src/components/UptimeGauge.tsx
src/page/ProbesPage.tsx

This PR:
- Alphabetizes the list of probes by name (fixes https://github.com/grafana/synthetic-monitoring-app/issues/57)
- Changes the "Uptime" label to "Success rate" (fixes https://github.com/grafana/synthetic-monitoring-app/issues/58)

chore: alphabetize probe list, change uptime label

---

src/components/CheckEditor.tsx
src/types.ts

fixes https://github.com/grafana/synthetic-monitoring-app/issues/16
The form was previously ignoring errors on submit. This pr adds an alert to the bottom of the page

fix: show error if check update/save fails

---

src/components/CheckEditor.tsx

fixes https://github.com/grafana/synthetic-monitoring-app/issues/35
Check will now load without probe values:

fix: handle editing check with no probes

---

package.json
src/validation.ts
yarn.lock

Fixes https://github.com/grafana/synthetic-monitoring-app/issues/77 (sort of)
Pulls in an external [url validation library](https://github.com/ogt/valid-url) to handle more URL validation cases

chore: use external library for url validation

---

src/RootPage.tsx
src/__mocks__/utils.ts
src/components/CheckHealth.test.tsx
src/components/CheckHealth.tsx
src/components/CheckList.tsx
src/components/InstanceContext.ts
src/hooks/useMetricData.ts
src/utils.ts

Currently we have a bit of prop drilling with the `instance` class which is muddying component APIs, increasing testing complexity, and requiring duplicative code when doing things like fetching metric data. This is the first step in extracting that out by putting the `instance` in a context in the `RootPage`. This allows for creating custom hooks that handle the currently duplicative logic and will allow us to get rid of the prop drilling in future PRs. 
This PR:
- Puts `instance` in a context
- Creates a custom hook that accesses the instance context and fetches metric data
- Refactors the CheckHealth component to use the new custom hook

Refactor check health

---

src/components/http/HttpSettings.tsx

fix: include saved tls config in http settings form

---

src/components/CheckEditor/CheckEditor.tsx
src/components/CheckEditor/CheckProbes.tsx
src/components/CheckEditor/CheckSettings.tsx
src/components/CheckEditor/ProbeOptions.tsx
src/components/Collapse.tsx
src/components/DnsSettings.test.tsx
src/components/DnsSettings.tsx
src/components/DnsValidatorForm.tsx
src/components/LabelField.tsx
src/components/ListInput.tsx
src/components/PingSettings.tsx
src/components/SliderInput.tsx
src/components/Subheader.tsx
src/components/TcpSettings/TcpSettings.tsx
src/components/TenantAPISetupForm.tsx
src/components/http/AuthSettings.tsx
src/components/http/HttpSettings.tsx
src/page/ProbesPage.test.tsx
src/types.ts

This PR rearranges the check editing experience:
- Collapses are restyled to meet design spec
- Nested collapses are removed and flattened out
- Label inputs are moved to advanced options in every check type
- Common fields for all check types are broken up into sections
- Frequency and timeout fields are converted to a combination slider/input component
Before: 
After:

Probe options

---

src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/constants.ts
src/components/http/HttpSettings.tsx
src/types.ts

- Moves HTTP SSL options from two switchers to one dropdown
- Changes HTTP validation fields to lay out vertically instead of horizontally
Before:
After:

Http ssl options

---

jest.config.js

Jest is too aggressive about running tests in parallel. It seems there's
something about the CheckEditor test suite that causes it to use more
memory than the other tests, so when running on all CPUs, it chews up
memory like nothing.
Reduce maxWorkers to 25% of the available CPUs as a guess... on my
machine, going above 25% does not reduce the test time (and in fact
going above 50% starts to increase it). I would happily keep it at 1 or
2, as that doesn't increase the total run time by any significant
amount.

chore: reduce maximum Jest workers

---

src/plugin.json

By adding defaultNav it makes clicking on the sidenav app icon go this page.  Noticed that nothing happened when I clicked the synthetic monitoring icon.

Navigation: Make Home the default page

---

scripts/production-release.sh

`${GIT_TAG//v}` is bash, not POSIX, so change /bin/sh to /bin/bash
md5sum outputs a '-' for the filename when working against stdin, so
make sure we don't pass that to curl (gcom).

chore: production-release.sh script needs bash

---

src/dashboards/sm-dns.json
src/dashboards/sm-http.json
src/dashboards/sm-ping.json
src/dashboards/sm-summary.json

We did the following renames in the probes to prevents problems down the
road:
* probe_success_sum to probe_all_success_sum
* probe_success_count to probe_all_success_count
* probe_dns_duration_seconds_count to probe_dns_all_duration_seconds_count
* probe_dns_duration_seconds_sum to probe_dns_all_duration_seconds_sum
* probe_http_duration_seconds_count to probe_http_all_duration_seconds_count
* probe_http_duration_seconds_sum to probe_http_all_duration_seconds_sum
* probe_icmp_duration_seconds_count to probe_icmp_all_duration_seconds_count
* probe_icmp_duration_seconds_sum to probe_icmp_all_duration_seconds_sum
* probe_tcp_duration_seconds_count to probe_tcp_all_duration_seconds_count
* probe_tcp_duration_seconds_sum to probe_tcp_all_duration_seconds_sum
This renames causes the panels not …

fix: update queries that use the renamed metrics

---

src/components/UptimeGauge.tsx
src/dashboards/sm-tcp.json

TCP was missing from the previous change.

fix: update TCP queries to use old and new metric names

---

src/RootPage.tsx
src/components/DashboardList.tsx
src/types.ts

When the metrics underpinning dashboard queries in the SM dashboard templates change, it breaks the dashboards unless users navigate to `Plugin config` => click on `Update` => click `Update` for each dashboard that has changes. This pr would check for dashboard template changes and present a modal that prompts the user to update them when they visit the SM plugin UI.

fix: auto update dashboards on UI load

---

src/dashboards/sm-dns.json
src/dashboards/sm-http.json
src/dashboards/sm-ping.json
src/dashboards/sm-tcp.json

In the DNS dashboard, the query is wrong, as it should be summing by
probe and not phase to coincide with the panel's description. In the
same panel, the legend should use the probe label, not the phase.
The the HTTP dashboard, the query is correct but the legend has the same
issue. Same goes for ping and TCP dashboards.
Also fix some casing issues in the panel titles.
Fixes #146.

fix: legend displays "Value" instead of probe name

---

scripts/production-release
scripts/staging-install.sh
src/components/InstanceProvider.tsx
src/components/PluginTabs.tsx
src/datasource/types.ts
src/types.ts
src/utils.ts

This handles an edge case in the non-provisioned flow for folks that already have the plugin installed in cloud. Previously they were getting stuck in a broken state, but now the upgrade will be transparent.

fix: handle unprovisioned cloud bootstrapping

---

package.json
src/components/AlertAnnotations.tsx
src/components/AlertLabels.tsx
src/components/Alerting.tsx
src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckEditor/CheckEditor.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/Collapse.tsx
src/components/InstanceProvider.tsx
src/components/SubCollapse.tsx
src/components/constants.ts
src/datasource/__mocks__/DataSource.ts
src/hooks/useAlerts.ts
src/page/ChecksPage.tsx
src/page/WelcomePage.tsx
src/types.ts
yarn.lock

What this PR does:
Adds the ability to create an alert rule from the synthetic monitoring UI. It's meant to be a one way operation, it allows users to create a rule, but pushes them to alerting-ui if a rule is already created. Closes #160 
Creation:
Editing:
Rule created in alerting-ui:
Running on prem:

Add alerts

---

src/validation.test.ts
src/validation.ts

fix: allow ipv6 hostnames for http checks

---

src/components/AlertAnnotations.tsx
src/components/AlertLabels.tsx
src/components/Alerting.tsx
src/components/CheckEditor/CheckEditor.test.tsx

We have a bug with creating alerts. We didn't quite map the labels and annotations correctly when we moved to adding multiple alert rules.

fix: annotation and labels in alerts not getting sent to ruler

---

src/hooks/useAlerts.ts

We are currently trying to send `severity` as it's own key in an alert rule, which doesn't exist. It seems like the convention is to send `severity` as a label instead. https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/

fix: add severity as an alert rule label

---

src/components/Alerting.tsx
src/components/CheckEditor/CheckEditor.test.tsx

The alerts implementation for SM checks is changing so any new checks being created should not be able to create alert rules from the check. Any existing alert rules are now linked to Cloud Alerting UI where users can edit them.

fix: hide alerts for new checks

---

src/components/CheckEditor/CheckEditor.tsx

A fix for check deletion. When the user would delete a check it would open a modal and delete the check via an API but it wasn't closing the modal after deletion and navigating back to the checks page.

fix: renavigate to checks page after deleting check

---

src/checkUsageCalc.test.ts
src/checkUsageCalc.ts
src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckEditor/CheckEditor.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/CheckHealth.test.tsx
src/components/CheckUsage.tsx
src/components/HorizonalCheckboxField.tsx
src/components/TLSConfig.tsx
src/components/constants.ts
src/components/http/HttpSettings.tsx
src/types.ts
src/validation.test.ts

Adds a field to the form for choosing standard (basic) or advanced metrics. Still need to work out the wording. @teddyba the Checkbox component in Grafana UI doesn't allow for elements in the description field, just a simple string. Meaning we can't put an anchor tag linking to the docs page. I can see about opening a PR to make a change but we also might be able to come up with a different solution.

Metric reduction form option

---

package.json
src/components/CheckEditor/CheckEditor.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/TLSConfig.tsx
src/types.ts
src/utils.ts
yarn.lock

Resolves #186 
The api is expecting a base64 encoded byte value, and we are sending a plain string. This PR translates user input to base64 if it isn't base64 already, and translates it back when editing.
There is also a little fix for ca cert fields that were passing the entire errors object to field errors instead of the just the error message, which makes the FieldError component error out.

fix: update tcp query response to send and parse base64

---

.circleci/config.yml

Updates to the new toolkit process used in grafana 7.4

chore: add plugin signing step to ci

---

src/components/ConfigActions.test.tsx
src/components/ConfigActions.tsx
src/components/DisablePluginModal.tsx
src/page/ConfigPage.tsx

When I updated the config page, I mistakenly believed it would no longer be possible for users (both on-prem and in cloud) to have the plugin installed but disabled, and removed the enable function. This PR does a few things:
- Adds and "enable" action to the plugin config page
- Disables the plugin in Grafana on disable (instead of just with the SM API)
- Pins the plugin on enable

fix: add plugin enable action

---

src/datasource/DataSource.ts

Fixes #182 
I fixed the typo in "onelineChange", which now is "onlineChange".

Fix typo in DataSource probes query

---

src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/TLSConfig.tsx
src/components/constants.ts
src/validation.test.ts
src/validation.ts

This PR adds some validation and guidance for adding certs/keys to HTTP and TCP checks. It does a few things:
- Conditionally presents base64 decoded values to the user for preexisting checks. If the certificate has a valid PEM header and footer, the plugin presents the decoded value, if it does _not_, it presents the raw base64.
- Adds form validation the presence of a PEM header and footer for both certificates and keys
- Adds some help text to notify the user that they have to use a PEM format certificate/key

Specify pem cert

---

src/components/Alerting.test.tsx
src/components/Alerting.tsx
src/hooks/useAlerts.ts

Current errors fetching alert rules result in an endless spinner. This PR surfaces the error in the UI and stops the spinning.

chore: expose errors when fetching alerts

---

src/components/AlertRuleForm.tsx

Fixes #225 
The wording in the alert edit form was inverted, it used to say "Checks marked with a sensitivity level of <level> with fire an alert if <percent> report connection errors", but the value we ask for is the _success_ rate, not the error rate. Updates to reflect reality are here:

fix: corrects alert expression wording in alert edit form

---

src/components/CheckList.tsx
src/components/CheckListItem/CheckItemActionButtons.tsx

The plugin was using ButtonGroup without a need for it, which crashes the plugin for Grafana 7.3

fix: prevent crashing on grafana v7.3

---

src/validation.test.ts
src/validation.ts

fixes #258 
This updates the frontend DNS target validation to mimic what's happening in the [SM agent DNS target validation](https://github.com/grafana/synthetic-monitoring-agent/blob/e6657cf8cd5697e84d812b9c03d3260c981f4769/pkg/pb/synthetic_monitoring/checks_extra.go#L482)

fix: allow trailing dots in DNS targets

---

__mocks__/@grafana/runtime.ts
src/components/ConfigActions.tsx
src/components/DisablePluginModal.tsx
src/datasource/DataSource.ts
src/utils.ts

We were using the deprecated `datasourceRequest` method for all our datasource interactions. Changing to the future proofed `fetch`. The `fetch` method returns an observable, and in order to limit the scope of the change I just converted them to promises.

chore: remove deprecated datasource method

---

__mocks__/@grafana/ui.tsx
src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckEditor/checkFormTransformations.ts
src/components/CheckList.test.tsx
src/components/constants.ts
src/components/http/HttpSettings.tsx
src/types.ts
src/validation.test.ts

Closes #237 
Depends on https://github.com/grafana/synthetic-monitoring-agent/issues/124
Adds a selector for HTTP checks to allow decompressing compressed responses.

Compression algo

---

src/components/App.tsx
src/components/FeatureFlagProvider.tsx
src/contexts/FeatureFlagContext.ts
src/hooks/useFeatureFlag.test.tsx
src/hooks/useFeatureFlag.ts
src/types.ts

This PR adds in some infrastructure for using feature flags. It creates a feature flag context and a hook that can read flags that can come from either the URL or the `config.ini` file.

Add feature flag infrastructure

---

src/dashboards/sm-dns.json
src/dashboards/sm-http.json
src/dashboards/sm-ping.json
src/dashboards/sm-summary.json
src/dashboards/sm-tcp.json

Add a "reachability" panel to all dashboards (and a reachability column
to the summary). This reflects the fact that some probes might fail to
reach a given target because of network errors between the probe and the
target, not associated to either of them.
Also redefine uptime a measure of how much time the target was reachable
by any probe vs unreachable from all probes.
Fixes #

Feature: add "reachability" to dashboards

---

src/components/CheckList.tsx
src/components/ChecksVisualization/Hexagon.tsx
src/components/ChecksVisualization/checksVizUtils.ts
src/components/SuccessRateContextProvider.tsx
src/components/SuccessRateGauge.test.tsx
src/components/SuccessRateGauge.tsx
src/contexts/SuccessRateContext.ts
src/page/ProbesPage.tsx
src/utils.ts

- Moves threshold calculation for success rates to a shared utilty
- Adds a warning threshold
- Changes the threshold limits to:
- \> 99.5% sucess
- \> 99% warning
- < 99% error
- Moves threshold colors to a shared utility

refactor: move threshold calculation and coloring to a common utility

---

src/analytics.ts
src/components/CheckEditor/CheckEditor.tsx
src/components/ProbeEditor.tsx
src/components/UnprovisionedSetup.tsx
src/page/ChecksPage.tsx
src/page/ProbesPage.tsx
src/page/WelcomePage.tsx

Following the example from the onboarding plugin, checking to see if GA is present in the page and sending events. I deliberately only added a few events to start

chore: add some analytics to the setup flow

---

src/components/TenantView/TenantView.tsx

Adds the apiHost url to the plugin config page
closes #289 
closes #263

fix: add backend host to plugin config page

---

src/components/CheckList.tsx
src/components/ChecksVisualization/ChecksVisualization.test.tsx
src/components/ChecksVisualization/ChecksVisualization.tsx
src/components/ChecksVisualization/IconOverlay.tsx
src/components/SuccessRateContextProvider.tsx
src/components/constants.ts
src/contexts/SuccessRateContext.ts
src/utils.ts

Our check visualization view isn't very accessible, because the only dimension differentiating the check status is color. This PR adds a toggle which will overlay icons onto the viz so they it's easier to see a distinction.
Without icons simulating achromatopsia:
With icons simulating achromatopsia:

Viz icon overlay

---

src/components/TLSConfig.tsx

Fix a small typo in HTTP check TLS settings: `muse` -> `must`

fix: fix typo in http TLS setting label

---

src/components/CheckFormAlert.tsx

This adds a little help note to the alerting section of the create check form. I also updated to the new theme utilities while I was making changes in the component.

fix: add some help text around less frequent checks and alert flapping

---

src/components/SuccessRateGauge.tsx

We need to align the naming of our measurements. The app was showing `Success Rate`, which is referred to as `Reachability` in the dashboards, so I changed the app to match the dashboards.

fix: rename the success rate panels to reachability

---

src/components/CheckEditor/checkFormTransformations.ts
src/components/constants.ts

HTTP is the most common check type. We had been showing PING as the default option, but it makes more sense to have HTTP be first.
Closes #330

fix: make HTTP the default check type

---

scripts/run-local.sh

The worldmap panel wasn't getting installed when running locally, passing an environment variable does the trick

chore: install worldmap panel in docker container

---

src/components/CheckEditor/CheckEditor.test.tsx
src/components/http/HttpSettings.tsx
src/types.ts

This pr is to fix a gap we had in exposing http settings. BBE and the agent [support specifying a URL to proxy http check through](https://github.com/grafana/synthetic-monitoring-agent/blob/d4b802d910a1fd9e1288ecd7619e0cb51a74cf43/pkg/pb/synthetic_monitoring/checks.pb.go#L963), but we don't have an input for it in the plugin. 
This just adds a text input to allow users to specify a proxy url for http checks.

fix: expose proxy url setting in http check form

---

src/types.ts

We're currently sending `HTTP/2` as the http version value for checks that want to accept HTTP/2 checks, however the value needs to be `HTTP/2.0` for the check to succeed, according to this issue in BBE: https://github.com/prometheus/blackbox_exporter/issues/658

fix: http version 2 value

---

src/components/ProbeList.test.tsx
src/components/ProbeList.tsx

Fix display of labels on probes list page.
Before:
After:

fix(ui): probe label display on probes page

---

src/components/CheckList/CheckList.test.tsx
src/components/CheckList/CheckList.tsx
src/components/CheckList/actions.ts
src/components/CheckList/checkFilters.ts
src/components/constants.ts

A handful of changes to CheckList:
- all filters are stored in a central state object, the filtered list of checks responds to any changes to filter object
- moved all API actions into a separate file
- export a single filter matching function for readability
Next steps:
- the checks are ultimately rendered from `currentPageChecks` which isn't connected to our state, it feels like we could figure out a way to combine this with our filtered checks in an effort to hopefully avoid "derived state"
- `selectedChecks` and `selectAll` state can get out of sync if you manually select all checks, could be a low hanging follow-up to check if all are selected by comparing `selectedChecks` and the master list of checks, then we can remove another chunk of state

Checklist state refactor

---

src/components/CheckEditor/CheckEditor.tsx

The check type input isn't getting disabled by the wrapping `<Field>` component for some reason. It shouldn't be possible to change the type of the check once it's been created, and it will cause the app to crash if someone does.

fix: check type selector should be disabled on edit

---

src/components/CheckEditor/CheckEditor.test.tsx
src/components/CheckTarget.test.tsx
src/components/constants.ts
src/validation.test.ts

Currently the default server for DNS checks is set to an IPv4 address.
But users can choose to use IPv6 instead, at which point the IPv4
default address leads to the check constantly failing. This default will
work for both IPv4 and IPv6 without issue.
See this working in practice on this check here:
https://syntheticmonitoring.grafana.net/a/grafana-synthetic-monitoring-app/?page=checks&id=63

Default server for DNS to domain name

---

src/dashboards/sm-traceroute.json
src/datasource/DataSource.ts
src/datasource/traceroute-utils.ts
src/utils.ts

This PR does a few things for the traceroute dashboard:
- Adds a multiselect for probes
- Fixes the initial probe select not updating the node graph
- Make the node layout more useful by making unknown TTL nodes probe specific.
- Breaks out the overall trace timing by probe
Before:
After:

Traceroute multi probe vars

---

src/components/CheckEditor/checkFormTransformations.ts
src/components/TracerouteSettingsForm.tsx
src/components/constants.ts
src/types.ts

This PR adds a field for PTR lookup (which attemps a reverse DNS search for each hop's IP address). It also sets that on by default since it's a nicer output than just an IP address. Also generally aligns the configurable settings with what is available in the agent. 
Depends on https://github.com/grafana/synthetic-monitoring-agent/pull/239

fix: include ptr lookup in traceroute settings

---

scripts/custom.ini
src/components/PluginTabs.tsx
src/components/constants.ts
src/contexts/FeatureFlagContext.ts
src/dashboards/loader.ts

Depends on [#374 ](https://github.com/grafana/synthetic-monitoring-agent/pull/239) being deployed to prod (`v0.3.2` of the agent)

feat: turn on traceroute

---

src/components/AccessToken.tsx
src/components/Clipboard/Clipboard.tsx
src/components/ProgrammaticManagement.tsx
src/components/TenantSetup.tsx
src/components/TerraformConfig/TerraformConfig.test.tsx
src/components/TerraformConfig/TerraformConfig.tsx
src/components/TerraformConfig/index.ts
src/components/TerraformConfig/terraformConfigUtils.ts
src/components/TerraformConfig/terraformTypes.ts
src/datasource/DataSource.ts
src/page/ConfigPage.tsx

Closes https://github.com/grafana/synthetic-monitoring-app/issues/375
- Adds a button to generate a new SM access token on the plugin config page
- Adds a button to export current checks and private probes as terraform config in JSON
.

Gen terraform config

---

src/dashboards/sm-dns.json
src/dashboards/sm-http.json
src/dashboards/sm-ping.json
src/dashboards/sm-summary.json
src/dashboards/sm-tcp.json
src/datasource/__mocks__/DataSource.ts
src/plugin.json

This PR 
- removes the dependency on worldmap panel and uses the built in Geomap panel. 
- updates the error percentage chart on the summary dashboard to use the new timeseries panel
- Fixes the Y axis of the error percentage chart (otherwise they all look identical even if they have largely differing values)
- Changes the summary map panel to represent error rate instead of reachability (this keeps things consistent with the other dashboards, and makes problems more obvious)
- Changes the name of the DNS dashboard so it's consistent with the other dashboards

Use geomap panel

---

src/components/TerraformConfig/TerraformConfig.tsx

current tf import command doesn't mention a way to import probe auth token, fix that and link to tf providor docs

fix: terraform import command for probes & link to docs

---

src/plugin.json

keep worldmap dependency around till folks have updated the old dashboards that are using worldmap

chore: include worldmap panel dependency

---

src/components/TerraformConfig/TerraformConfig.test.tsx
src/components/TerraformConfig/TerraformConfig.tsx
src/components/TerraformConfig/terraformConfigUtils.ts

Depends on https://github.com/grafana/terraform-provider-grafana/pull/327 being merged/published

feat: include traceroute checks with terraform config

---

src/components/CheckListItem/CheckListItem.tsx
src/hooks/useUsageCalc.test.tsx
src/hooks/useUsageCalc.ts

Partially fixes https://github.com/grafana/synthetic-monitoring-app/issues/407
CheckList was calculating all checks as `<check_type>_ssl`, since (I think) the API is returning an empty set of TLS settings for every non-TLS check. This PR makes sure that there are actually settings present inside the check, and both calculations are the same if it is non-tls.
There is however another issue that during new/edit a check, we aren't watching TLS settings in our calculations. This will take a bit more refactoring so I figured a follow-up PR would be best for that.

fix: [cr] check class correctly in CheckList

---

src/components/AlertRuleForm.tsx
src/components/alertingTransformations.ts
src/components/constants.ts
src/types.ts

This is trying to make the extraction logic more generic, so that it
works with other alerts similar to the existing ones, but not exactly
like them.

chore: rework logic to extrac values from alert rules

---

CHANGELOG.md
package.json
src/components/CheckList/CheckFilterGroup.tsx
src/components/CheckList/CheckList.test.tsx
src/components/CheckList/CheckList.tsx
src/components/CheckList/EmptyCheckList.tsx

Re-arranged filters under a central dropdown, with some state to show when active/inactive. Also cut down on vertical rows after talking with Teddy about it.
Also changed the empty check list alert to use `<Alert />` since `<InfoBox />` is marked as deprecated.

feat: [cr] refactor of filtering UX, updates tests

---

src/components/TenantView/LinkedDatasourceView.tsx
src/datasource/DataSource.ts
src/datasource/types.ts
src/initialization-utils.ts
src/types.ts
src/utils.ts

This would be a first step towards fixing https://github.com/grafana/synthetic-monitoring-app/issues/419
I think ultimately to resolve this issue we're gonna need to do a few things that might be worth breaking into a few different PRs:
- Auto-update dashboards on plugin load (we can look at GEM for an example of how to do this)
- Auto-update the SM datasource JSON on load ([also reported as an issue for other reasons](https://github.com/grafana/synthetic-monitoring-app/issues/274))
- Update the cloud provisioning to include the uid

fix: try and use UIDs for datasources if they are available

---

src/components/Routing.tsx

When trying to initialize an unprovisioned plugin on a local instance, it's possible to get stuck in a never ending redirect loop. This should fix that.

fix: stop infite reloop on local unprovisioned setup

---

src/dashboards/sm-dns.json
src/dashboards/sm-http.json
src/dashboards/sm-ping.json
src/dashboards/sm-summary.json
src/dashboards/sm-tcp.json

The way we're referencing threshold values for the geomap panel in our dashboards is no longer valid. Currently no matter the value, everything is showing up green. This change makes error rate values drive the size of the bubble and the color.
Before
After

Geomap thresholds bug

---

src/components/ProbeList.tsx

Show probe region and type on list page
Fixes #454
UI before this feat:
UI After this feat

feat: display probe region and probe type on probe list page

---

src/components/CheckEditor/CheckEditor.tsx

Shows full error in case of submission error
Fixes #453
Maybe #435
Here is what it looks like with this fix:

fix: show full error in case of submission error

---

src/components/Routing.tsx

**Related Slack discussion:** https://raintank-corp.slack.com/archives/C01C4K8DETW/p1650966538006679
**Related issue:** https://github.com/grafana/grafana-plugin-examples/pull/71
We noticed a weird issue when trying to navigate between certain app plugins in Grafana: the URL was flickering but the actual navigation never or rarely happened. 
One of the reasons was that a `<Redirect>` component (for serving a "base url") initiated a redirect every time
the plugin was rendered, and like that it was overriding navigation happening between app plugins. Only redirecting when the URL matches the plugin's URL solves the issue. 
The best solution to this problem would be if the app plugin would never render again after we are "navigating away" from it, and this would need to be fixed in the core …

Routing: only redirect to the Home page if the URL matches the plugin

---

src/components/InstanceProvider.tsx
src/components/Routing.tsx
src/contexts/InstanceContext.ts

When running the plugin locally without provisioning it was getting stuck in an infinite redirect loop

fix: unprovisioned setup could get in an infinite loop

---

src/dashboards/sm-ping.json

In support ticket, a customer discovered that they are unable to edit the "Average latency" panel in the "Synthetic Monitoring Ping" dashboard provided by the SM App. The problem (as described in https://community.grafana.com/t/selecting-edit-on-panel-opens-edit-window-for-a-different-panel/5435/2) is that two panels have this in their JSON:
```
"id": 34,
```
By changing one of the panels to have id=33, that fixes the problem
n/a

Fix duplicate panel ID in this dashboard

---

src/components/TenantAPISetupForm.tsx

Noticed this strange orange link that goes to grafana.com, never seen an orange link in Grafana so did some minor tweaking to this link. Made links in the text instead and an extra one in the field description. 
Before:
After:

feat: minor ux tweaks to setup page

---

src/components/TerraformConfig/terraformConfigUtils.ts

I cannot find anything that says that resource names in terraform have a limit. I can find some blurb here and there about specific providers imposing limits on resource names, but that doesn't seem to come from terraform.
I tried with longer resource names and they work. I cannot find anything in the Grafana provider that limits that, either.
Fixes: grafana/support-escalations#4118 #482 

fix: remove limit on resource name lenght

---

src/components/CheckEditor/CheckEditor.tsx
src/components/CheckEditor/ProbeOptions.tsx
src/validation.ts

1) Traceroute checks have a default and immuatble timeout of 30 seconds; but all other checks should have an adjustable timeout from 1 to 10 seconds. Previously our error message misled users with non-traceroute checks to believe that they could adjust up to 30 seconds, which is inaccurate. So this PR fixes that to reflect the correct params.
2) Also fixed a bug that didnt clear the error messages from the slider input, even if the user changed their `checkType`
Fixes https://github.com/grafana/support-escalations/issues/4312
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/486
Fixes #

Fix: fix error for non-traceroutes; clear error if check type changes

---

src/components/constants.ts

fixes #475 
The labels for DNS regex validations were wonky. They were both different in language than for all the other check types and inverted the logic. This clarifies it so that users know the check will fail on a regex match unless the `invert match` option is selected.

chore: update the labels on dns regex validation

---

src/components/CheckEditor/CheckEditorExisting.test.tsx
src/components/HorizonalCheckboxField.tsx
src/components/SliderInput.tsx
src/components/http/HttpSettings.tsx

Fixes #483 
Shows an error if trying to validate the body of a HEAD request. Also fixes a couple little styling and alignment issues that have been creeping in.

fix: show error state if validating the body of an HTTP HEAD request

---

CHANGELOG.md
package.json
src/datasource/DataSource.ts

This resolves a bug that got reported where dashboard panels were reporting no data in the traceroute node panel

fix: variable interpolation in traceroute dashboard queries

---

src/components/CheckList/CheckFilterGroup.tsx

Light theme had been showing dark theme backgrounds

fix: use theme colors in filter dropdown

---

src/components/DashboardList.tsx
src/components/InstanceProvider.tsx
src/components/LinkedDatasourceView.tsx
src/datasource/ConfigEditor.tsx
src/datasource/DataSource.ts
src/page/ConfigPage.tsx
src/page/WelcomePage.tsx

Fixes a problem where renaming a stack causes the synthetics configuration to go sideways. The root issue is that the SM plugin is referencing datasources by name, and the name changes when the stack changes. The fix is to reference datasources by UID instead (which are standard in cloud). 
In cases where the _name_ of the datasource doesn't match but there is a UID that SM can use, a modal will get shown notifying the user of the situation and allow them to proceed
This doesn't fix the problem for existing stacks that are already initialized without a UID.

Match ds on uid

---

src/page/HomePage.tsx

A slash at the end caused a 404 error.
Closes #554

fix: Scenes: Broken summary dashboard link in Home

---

src/page/HomePage.tsx

Under scenes, the dashboard box in the Summary page showed the text dashboards twice for each dashboard.
Closes #555

fix: Repeated `dashboard` in Home

---

dev/provisioning/plugins/example.yaml
src/plugin.json

Removes `grafana-worldmap-panel` from the list of dependant plugins in plugin.json.
`grafana-worldmap-panel` is deprecated, and it was replaced with `geomap` in #398
However, the dependency in `plugin.json` was not removed. This will cause Grafana to attempt to install `grafana-worldmap-panel` when installing `synthetic-monitoring-app`, even if it's not required anymore.
This is a problem because `grafana-worldmap-panel` uses Angular, which is being removed and will causes issues when installing `synthetic-monitoring-app` if [Angular is disabled](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#angular_support_enabled) in Grafana via config (which will also be the default in the future)
Fixes …

chore: removed grafana-worldmap-panel dependency in plugin.json

---

README.md

Updated URL to point the worldping project, rather than a 404 at grafana.net

fix: update URL for worldping project

---

src/components/Alerting.tsx

Users with a viewer role will get a warning if they try and change things, editors will be able to edit

fix: allow non admin viewers to view alerts

---

dev/provisioning/datasources/example.yaml

When setting up my dev environment I used the examples that were provided in the provisioning folders. I noticed later on that the `readMe.md` had the correct shape that was expected with more accurate comments of what is expected for `basicAuthPassword` and `basicAuthUser`.

fix: update provisioning examples to match readme

---

src/components/CheckEditor/CheckEditorExisting.test.tsx
src/components/CheckEditor/CheckEditorNew.test.tsx
src/components/CheckList/CheckList.test.tsx
src/components/MultiHttp/MultiHttpNew.test.tsx
src/components/MultiHttp/MultiHttpSettingsForm.test.tsx
src/components/ProbeEditor/ProbeEditor.test.tsx
src/components/QueryParams.tsx
src/components/Thresholds/ThresholdGlobalSettings.test.tsx
src/hooks/useUsageCalc.test.tsx
src/page/ChecksPage.test.tsx
src/page/ProbesPage.test.tsx
src/test/render.tsx

Part 2 of reducing the boilerplate to writing comprehensive tests. 
Added a Router and the FeatureFlagProvider to the customRender. Now utilising routes and feature flags is as simple as adding additional options to the render function, rather than importing the correct dependencies.

Feat: Add Router and FeatureFlagProvider to the customRender to reduce test boilerplate

---

dev/provisioning/plugins/example.yaml

Saw [this PR](https://github.com/grafana/synthetic-monitoring-app/pull/627), so thought it would be good to keep them aligned 😃

fix: align plugin example provisioning file with readMe version

---

src/components/TerraformConfig/terraformConfigUtils.ts
src/components/TerraformConfig/terraformTypes.ts
src/hooks/useTerraformConfig.test.tsx

Makes the "Generate Config" button in the Terraform section of the plugin config page handle MultiHTTP checks

Add multihttp to terraform

---

src/components/BigValueTitle.tsx
src/components/CheckListItem/CheckListItem.tsx
src/components/LatencyGauge.tsx
src/components/ProbeList.tsx
src/components/ProbeStatus.tsx
src/components/SuccessRateGauge.test.tsx
src/components/SuccessRateGauge.tsx
src/components/constants.ts
src/scenes/Common/reachabilityStat.ts
src/scenes/Common/uptimeStat.ts

Thanks for the feedback on the first try! Here's the next take. It's still a little small on the probes view, but overall much better than the first attempt: 
I opted not to wrap BigValue, but instead just created a BigValueTitle component. Wrapping BigValue felt like it was an opportunity to redefine the API of the BigValue component, but that was more bite than I wanted to chew today 😅. Happy to change that if it feels important.

fix: add a description tooltip to uptime and reachability stats 

---

src/components/MultiHttp/MultiHttpCollapse.tsx
src/components/MultiHttp/MultiHttpSettingsForm.tsx
src/components/MultiHttp/MultiHttpSettingsForm.utils.ts
src/components/MultiHttp/MultiHttpTypes.ts
src/components/MultiHttp/Tabs/AssertionsTab.tsx
src/components/MultiHttp/Tabs/TabSection.tsx
src/components/MultiHttp/Tabs/Tabs.tsx
src/types.ts

**Before**
- Field / Error misalignments.
- Request header non-keyboard accessible
- Difficult to spot errors on save
https://github.com/grafana/synthetic-monitoring-app/assets/6906380/7a9dfbf4-0d17-4bcf-a76a-b304497cc03e
**After**
- Aligned fields / errors.
- Keyboard-accessible request header
- Automatically opens the first collapsed request header and goes to the first tab with errors. One known issue with this implementation is that @grafana/ui does not forward the ref to the Select in a react-hook-form Controller, so it doesn't automatically focus some fields. I'll put another PR up tomorrow to address this as I know another workaround that is a little bit involved.
https://github.com/grafana/synthetic-monitoring-app/assets/6906380/3abe4097-955d-4651-a7f1-40b51dd79ebd

Fix: Multihttp tabs styling and open first request tab with error

---

src/page/HomePage.tsx

- The "Learn more about creating checks programmatically" link isn't quite working right.  It takes you to the top of the docs page.  This fix will take people to the expected heading
- <img width="529" alt="image" src="https://github.com/grafana/synthetic-monitoring-app/assets/7903188/6664a632-df37-4ad0-9e9b-40442aaee233">
Video clip
https://github.com/grafana/synthetic-monitoring-app/assets/7903188/5ec9fab2-144b-4583-84a8-edb1dcdbede2

fix 'create checks programmatically' link

---

src/components/SuccessRateContextProvider.tsx
src/page/ProbeRouter.tsx

This is a **very temporary fix** to get the success gauges working again.
The `SuccessRateContextProvider` component is very confusing and is starting to show its age as it very easily broke with what looks like a sensible change from [this PR](https://github.com/grafana/synthetic-monitoring-app/pull/647). I'm going to loop back to refactoring this when I look at adding `react-query` after the Probes PR I am about to put up.
**Before:**
**After:**

fix: temporary fix for success gauges

---

src/page/HomePage.tsx
src/scenes/SCRIPTED/dataTransferred.ts
src/scenes/SCRIPTED/expectedResponse.ts
src/scenes/SCRIPTED/scriptedScene.ts
src/scenes/SCRIPTED/successRateByUrl.ts
src/scenes/SCRIPTED/timingByTarget.ts

Adds a few visualizations to the scripted dashboard. These could also be used by MultiHTTP. I'm just trying to gather up a collection of charts before breaking them out into a more interactive experience

chore: add some charts using k6 data

---

src/scenes/ExplorablePanel.ts

Adds the ability to copy panel json to the clipboard from scenes so folks can add those panels to their own dashboards

feat: add copy panel json

---

src/scenes/SCRIPTED/AssertionsTable/AssertionsTableRow.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/ResultsByTargetTableRow.tsx

With no indentation the scene can be really hard to parse:
Adding a bit of space with a different background color helps

fix: indent expandable rows in the scripted scene

---

src/faro.ts
src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
src/scenes/SCRIPTED/AssertionsTable/successOverTimeByProbe.ts

Assertions that only ever fail have an unpredictable data structure when querying, so this make the display handle that. Also escapes quotes in an interpolated query

Multihttp assertion bug

---

src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/ResultsByTargetTableRow.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/errorRateByTargetProbe.ts
src/scenes/SCRIPTED/ResultsByTargetTable/latencyByPhaseTarget.ts

I realized some of the queries in the MultiHTTP/Scripted dashboard were misleading/slight incorrect. Hopefully this rectifies all those issues. 
Specifically success rate by URL, latency by URL/phase, and success rate by URL/probe were all aggregating incorrectly.

Fix a few query errors

---

package.json
src/faro.ts
yarn.lock

Currently our frontend observability is routed to a standalone instance that we don't look at. This will put that data in ops.

chore: update Faro to send telemetry to ops

---

src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/resultsByTargetTableQueries.ts
src/scenes/SCRIPTED/ResultsByTargetTable/utils.ts

Successive refetches of metric data was resulting in the results by URL table getting scrambled and mixing up which results are related to which URL. I had assumed that data frames were consistent across queries sent out by the same runner (i.e. if the index of the value for URL A is 1 in the success rate query, it will also be 1 in the latency query). Turns out that is _not_ the case, so we have to be defensive and sift through the data in order to pluck the results from the correct place every time.

fix: results by URL table wasnt handling out of order updates correctly

---

src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/utils.ts

I didn't account for the fact multihttp and scripted checks have different label names in my previous fixes 🤦

fix: account for multihttp having different label names

---

dev/custom.ini
docker-compose.yaml
package.json
src/components/CheckListItem/CheckItemActionButtons.tsx
src/page/CheckRouter.tsx
src/page/DashboardPage.tsx
src/page/HomePage.tsx
src/scenes/Common/variables.ts
src/scenes/DNS/dnsScene.ts
src/scenes/HTTP/httpScene.ts
src/scenes/PING/pingScene.ts
src/scenes/SCRIPTED/scriptedScene.ts
src/scenes/Summary/summaryScene.ts
src/scenes/Summary/summaryTable.ts
src/scenes/Summary/summaryTable_DEPRECATED.ts
src/scenes/TCP/getTcpScene.ts
src/scenes/Traceroute/getTracerouteScene.ts
src/scenes/dashboardSceneApp.ts
src/types.ts
yarn.lock

The next step here will be to rework the summary dashboard and use it as the home page. I want to tackle that in a separate PR, though. 
This changes should be completely sealed behind the `synthetics-per-check-dashboards` feature toggle

chore: add check specific dashboard route

---

src/components/CheckEditor/CheckEditor.tsx
src/components/K6CheckCodeEditor.tsx
src/components/MultiHttp/MultiHttpSettingsForm.tsx

During one of the refactors I was experimenting with going back to the previous location rather than defaulting to going back to the check list but there are lots of instances that isn't desirable, so reverting it back to how it was.

fix: updated navigation after check creation

---

src/components/CheckEditor/checkFormTransformations.ts
src/types.ts

Small bug when going to a tcp check directly it wasn't rendering correctly. Think this was a regression introduced last week.

fix: tcp queryresponse fix

---

jest.config.js
src/components/CheckForm/MultiHttpExisting.test.tsx
src/page/ChecksPage.test.tsx

The MultiHTTP tests were spewing lots of act errors. I think the `waitFor` was originally put in there when render behaved differently?
I was also getting tests timing out a lot, so I turned the global timeout back on

chore: clean up test output

---

src/components/CheckTestResultsModal.tsx
src/datasource/traceroute-utils.ts

Grafana 11 is being rolled out in dev and ops and they have fully deprecated and removed `ArrayVector` in this major version bump.
The issue was reported in this [Slack thread](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1709137607374859). According to the notes in the Grafana documentation the fix is just to use a simple array instead.

fix: remove deprecated arrayVector

---

src/scenes/Summary/summaryScene.ts
src/scenes/behaviors/HiddenLayoutItemBehavior.ts
src/scenes/behaviors/HideableObject.ts

Viewers:
Editors/Admins:
I also added a behavior that allows showing/hiding based on a condition (copied from the scenes repo). I ended up not being able to use it because this particular element is part of the scene controls, not part of the layout tree, but figure it will be useful down the line

fix: hide the add new check button if a user doesnt have permissions

---

src/components/Card/Card.tsx
src/components/Card/index.ts
src/components/ChooseCheckType.tsx
src/components/ProbeCard/ProbeCard.tsx
src/page/ChecksPage.test.tsx

The `@grafana/ui` `<Card />` component is _far_ too opinionated (committing us to a grid structure, using h2s for titles, etc). for what it should be providing (a simple card UI...) but is a common design pattern that we want to utilise throughout the application.
The original problem that prompted me to go down this route of refactoring is I wanted to open up all the Checks from 'choose-a-check' side-by-side by using the browser's `cmd + click` to open each in a new window but couldn't do that because the current implementation is based on navigation via a button rather than a link (which has accessibility issues, too).
https://github.com/grafana/synthetic-monitoring-app/assets/6906380/717f192b-75fe-4e30-8a2d-d2a588a6baf4
Created a re-usable and less opinionated `Card` component which we …

Synthetic monitoring card component

---

src/scenes/Common/avgLatencyStat.ts
src/scenes/Common/divideSumByCountTransformation.ts
src/scenes/Common/errorRateMap.ts
src/scenes/Common/reachabilityStat.ts
src/scenes/Common/uptimeStat.ts
src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/Summary/errorPctTimeseries.ts
src/scenes/Summary/errorRateMap.ts
src/scenes/Summary/latencyTimeseries.ts
src/scenes/Summary/summaryTable.ts

Fixes #667 
This change should be entirely transparent to users, it moves most of the calculations in our dashboards from prometheus into Grafana transformations. That, in turn, allows us to query longer time ranges.

Fix long range queries

---

src/components/CheckEditor/CheckEditorExisting.test.tsx
src/components/CheckEditor/FormComponents/DNSCheckResponseMatches.tsx
src/components/CheckEditor/FormComponents/HttpCheckRegExValidation.tsx
src/components/CheckEditor/FormComponents/MultiHttpCheckRequests.tsx
src/components/CheckEditor/testHelpers.ts
src/components/CheckForm/CheckEditor.test.tsx
src/components/CheckForm/MultiHttpExisting.test.tsx
src/components/CheckForm/MultiHttpNew.test.tsx
src/components/CheckList/CheckList.test.tsx
src/components/ConfigActions.test.tsx
src/components/MultiHttp/MultiHttpCollapse.tsx
src/components/ProbeEditor/ProbeEditor.test.tsx
src/components/QueryParamInput.tsx
src/components/QueryParams.test.tsx
src/components/QueryParams.tsx
src/components/ScriptedCheckCodeEditor.test.tsx
src/components/SliderInput.tsx
src/components/TerraformConfig/TerraformConfig.test.tsx
src/components/TimeSlider/TimeSlider.tsx
src/page/AlertingPage.test.tsx
src/page/ChecksPage.test.tsx
src/page/EditProbe/EditProbe.test.tsx
src/page/NewProbe/NewProbe.test.tsx
src/page/Probes/Probes.test.tsx
src/test/utils.ts

As [per this issue in testing-library](https://github.com/testing-library/dom-testing-library/issues/552), `*byRole` selectors can have a significant performance impact. We have seen some flaky tests locally and it is unclear if this is contributing to them, so this is a precautionary step to try and reduce variables and debug the root cause.
Remove all `*ByRole` selectors and put in equivalents. To help convert the selectors I also added some accessibility help to certain inputs, as well as reduce a bit of test noise by correcting the `append` method for adding requests to the multihttp check form.
To be honest, this doesn't speed up the tests as much as I was hoping but I think it is worth doing anyway to see if it helps resolve some of the flakiness. It takes about 10% or so off after …

fix: remove byRole selectors in tests and add some a11y to inputs

---

src/components/ProbeEditor/ProbeEditor.test.tsx
src/components/ProbeEditor/ProbeEditor.tsx
src/components/ProbeRegionsSelect/ProbeRegionsSelect.tsx

Small regression with the probe region not being disabled after the [probe region select PR](https://github.com/grafana/synthetic-monitoring-app/pull/710) went in. 
Also noticed that the tests weren't running because we weren't awaiting them to run so that's why the test didn't pick up on it. 🤦

fix: new region select disabled and fixed async probe form tests

---

src/components/CheckEditor/FormComponents/CheckIpVersion.tsx
src/components/CheckEditor/TCPCheck.test.tsx
src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx

Noticed a copy and paste mistake when working on the alerting story this morning.
Added a regression test to pick up on it, with the goal that we can slowly add tests to every input in every check type as time goes on. At the moment our tests are pretty large and test multiple things at once but we should think about doing smaller more targeted integration testing like the one I've added for increased confidence.

fix: fix tcp ip version and add associated test

---

src/components/CheckEditor/CheckEditorNew.test.tsx
src/components/CheckEditor/HttpCheck.test.tsx
src/components/CheckEditor/checkFormTransformations.ts

In a recent refactor and to appease React form / React ref errors in the console (such as controlling uncontrolled fields...) I set some fields with empty strings, this had an unexpected consequence of being included in the payload which can mess up authentication to many services.
This problem was included in [this internal Slack thread](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1712732546959319).
Going to make a ticket to check through if any other fields which are considered empty should also be omitted, as well as improving the UI so that if the include checkbox is not ticked it won't include the payload either.

fix: remove basicAuth if not explicitely added

---

CHANGELOG.md
src/scenes/Common/uptimeStat.ts
src/scenes/utils.ts

I had thought the min step had to be increased in order to support long range queries and checks with larger frequencies, but it appears I was mistaken.

fix: allow min step to be 1 minute in dashboard queries

---

src/data/useLatency.ts

The latency column for scripted check isn't really latency right now - it's the average run duration of the k6 script, which can include lots of non-request overhead such as k6 startup time. 
For multihttp we take the average the http requests rather than the average execution duration of the test. 
This PR applies the same to scripted checks.  
The only downside is that scripted checks can include other protocols like websockets or grpc,  so we will not accurately capture average latency when those are used.   But in the interim, using http request duration average is better than the alternative of average execution duration.

scripted check latency: use avg of http requests duration

---

src/components/CheckEditor/CheckEditorNew.test.tsx
src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayouts/CheckDNSLayout.tsx
src/components/CheckForm/FormLayouts/CheckHttpLayout.tsx
src/components/CheckForm/FormLayouts/CheckMultiHttpLayout.tsx
src/components/CheckForm/FormLayouts/CheckPingLayout.tsx
src/components/CheckForm/FormLayouts/CheckScriptedLayout.tsx
src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
src/components/CheckForm/FormLayouts/CheckTracerouteLayout.tsx
src/components/ChooseCheckType.test.tsx
src/components/ChooseCheckType.tsx
src/components/LabelField/LabelField.test.tsx
src/components/LabelField/LabelField.tsx
src/components/ProbeEditor/ProbeEditor.tsx
src/data/useTenantLimits.ts
src/datasource/DataSource.ts
src/datasource/responses.types.ts
src/faro.ts
src/test/fixtures/tenants.ts
src/test/handlers/index.ts
src/test/handlers/tenants.ts
src/utils.ts

I'm a little unsure where the best place to gate access based on limits is. I definitely don't want it to be how it currently is (when you submit a form after filling it out), but there are other options than what I've done. Opinions welcome.
Fixes https://github.com/grafana/synthetic-monitoring/issues/49
No limits reached:
Overall limit reached:
Scripted limit reached:

chore: enforce tenant limits on the frontend

---

src/scenes/Common/allLogs.tsx
src/scenes/SCRIPTED/scriptedScene.ts

Untoggled:
Now toggled:
Hopefully this makes it easier to see _why_ a check failed. The one in this screenshot timed out. Before this change the logs were getting filtered by error level, and all the lines that preceded the actual error got filtered out.

fix: query logs by probe success instead of error level

---

src/components/CheckEditor/ProbeOptions.tsx
src/components/ProbeEditor/ProbeEditor.tsx
src/components/TerraformConfig/terraformConfigUtils.ts
src/page/NewProbe/NewProbe.tsx
src/test/fixtures/probes.ts
src/test/fixtures/terraform.ts
src/test/utils.ts
src/types.ts

Probes now have a `capabilities` key that allows them to communicate their preferences to the frontend. The only one that exists so far is whether to disable scripted checks or not, that allows us to prevent users from added scripted checks to non-AWS probes, and allows users to decide whether to run scripted checks on private probes

feat: add toggle to prevent scripted checks from running on probes

---

src/components/CheckEditor/FormComponents/CheckTarget.tsx
src/components/CheckEditor/FormComponents/RequestTargetInput.tsx

Every check that was using `CheckTarget` component could have the "Query Params" inputs rendered based on the `target` value. AFAIK, only `CheckType.HTTP` is using the "Query Params" part of `RequestTargetInput`.
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/766

Fix: only show query params for `CheckType.HTTP`

---

src/components/DocsLink/DocsLink.tsx
src/page/AlertingPage.tsx
src/scenes/SCRIPTED/AssertionsTable/AssertionsTable.tsx

1 - https://github.com/grafana/website/pull/19543 will update the SM Alerting documentation covering most of the info users need to understand how it works. 
In this PR, https://github.com/grafana/synthetic-monitoring-app/commit/ad5650fa244c24813e9e7244751dfa1bcdf9a1ed removes the reference to the outdated old post. 
If we want to include additional instructions, suggest adding to the documentation.
2 - Took the opportunity to update doc links due to doc reorganization. These links were working becuase redirects are in place, but thought it was a good idea to update them.

fix: update doc links

---

src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayout/FormLayout.tsx
src/components/CheckForm/FormLayouts/CheckDNSLayout.tsx
src/components/CheckForm/FormLayouts/CheckHttpLayout.tsx
src/components/CheckForm/FormLayouts/CheckPingLayout.tsx
src/components/CheckForm/FormLayouts/CheckScriptedLayout.tsx
src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
src/components/CheckForm/FormLayouts/CheckTracerouteLayout.tsx
src/components/CheckUsage.tsx
src/types.ts

Puts  usage on two lines so it doesn't wrap annoyingly
Also makes submission errors visible:

fix: submission errors off screen and usage layout

---

src/components/CheckForm/FormLayout/FormLayout.tsx
src/components/CodeEditor/CodeEditor.tsx

This fixes the autosuggest window wandering away from the cursor for the check editor. The actual fix is adding `          fixedOverflowWidgets: false,`, the rest is just reverting back the responsive layout. 
I'm not sure _why_. It has something to do with how Monaco handles overflows, and how `container` is sizing things, but I'm unsure what's going on there

fix: set fixed overflow widgets on monaco editor

---

src/scenes/Common/uptimeStat.ts

Uptime was calculating incorrectly for checks with frequencies of an hour because of some bad string parsing

fix: min steps with two digits having incorrect uptime

---

src/components/constants.ts

Traceroute checkk only accepts 30s as timeout. Since this was not specified in its default definition, it was falling back to the base check timeout, which specifies a TO of 3s.

fix: traceroute check default timeout

---

.config/jest/utils.js
src/components/CheckEditor/FormComponents/CheckIpVersion.tsx
src/components/CheckEditor/FormComponents/CheckUseTLS.tsx
src/components/CheckEditor/FormComponents/GRPCCheckService.tsx
src/components/CheckEditor/FormComponents/RequestTargetInput.tsx
src/components/CheckEditor/transformations/toFormValues.grpc.ts
src/components/CheckEditor/transformations/toPayload.grpc.ts
src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayouts/CheckGrpcLayout.tsx
src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
src/components/CheckList/CheckList.test.tsx
src/components/TLSConfig.tsx
src/components/TerraformConfig/terraformConfigUtils.ts
src/components/TerraformConfig/terraformTypes.ts
src/components/constants.ts
src/page/DashboardPage.tsx
src/scenes/GRPC/getGRPCScene.ts
src/types.ts
src/utils.types.ts
src/validation.ts

This PR enables creating of gRPC health checks.
gRPC checks must be enabled with `[feature_toggles]` in `config.ini` (`grpc-checks=true`).
Note: gRPC dashboard is only a placeholder dashboard. A new PR will be created to add a gRPC specific dashboard.
Note: Terraform is not yet setup for gRPC checks (in [terraform-provider-grafana](https://github.com/grafana/terraform-provider-grafana/))
Partly https://github.com/grafana/synthetic-monitoring/issues/47
To test this feature you may have to setup a local gRPC service that support health checks.
I've been using https://github.com/Sho2010/grpc-health-check as a local gRPC service, alongside a private probe running in docker.
Example …

feat: add UI for gRPC checks

---

src/components/CheckEditor/CheckEditorExisting.test.tsx
src/components/CheckEditor/FormComponents/HttpCheckSSLOptions.tsx
src/components/CheckEditor/HttpCheck.test.tsx
src/components/CheckEditor/transformations/toPayload.http.ts
src/components/constants.ts

Closes: https://github.com/grafana/synthetic-monitoring-app/issues/788
There was a regression when updating the payloads recently where we missed updating the onChange handler for the select in `<HttpCheckSSLOptions />`.
This fixes the regression and adds tests to ensure it doesn't break again in the future.

fix: fix onChange for ssl select and add tests

---

src/components/NameValueInput/NameValueInput.tsx

This PR adds some spacing between label elements when creating a Check. It also fixes the misalignment of the "remove" button next to each label input.
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/763
Before
After

fix: alignment and spacing for labels in Check creation form

---

src/components/CheckUsage.tsx

Our usage docs refer to "test executions per month", for example: https://grafana.com/docs/grafana-cloud/cost-management-and-billing/reduce-costs/synthetic-monitoring-costs/
The check creation flow & editing use the term "checks per month", which can cause some confusion.  This PR updates uses the term "test executions per month" to be consistent.
Somewhat related to https://github.com/grafana/synthetic-monitoring-app/issues/805
Before:
After:

Update usage details to use consistent naming "test executions"

---

src/scenes/Summary/summaryTable.ts

Fixes a regression from https://github.com/grafana/synthetic-monitoring-app/pull/801 where the check ID was missing from the path in the checks list, making it unable to load each check's individual dashboard.
**Before**
**After**
Reported in Slack https://raintank-corp.slack.com/archives/C0162C1K9E1/p1717612374226399

fix: bring back id in checks link from homepage dashboard

---

src/components/CheckEditor/FormComponents/HttpCheckBasicAuthorization.tsx
src/components/CheckEditor/FormComponents/HttpCheckBearerToken.tsx
src/components/PasswordField/PasswordField.test.tsx
src/components/PasswordField/PasswordField.tsx
src/schemas/forms/HttpCheckSchema.ts

The Authentication step for HTTP checks allows to configure a username and password. This password field was displaying the value entered by the user in clear text, posing a security concern.
This PR adds a `PasswordField` component that allows to mask/show the value in the input and uses it in Auth/bearer and password fields.
**Before**
**After**
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/795

fix: change password type to input on http auth config

---

src/components/LabelField/LabelField.tsx

Adds a link to the documentation in the section where users can add custom labels to their checks.
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/746
The "Read more" link takes you to https://grafana.com/docs/grafana-cloud/testing/synthetic-monitoring/analyze-results/custom-labels/#custom-labels

feat: add custom labels link to docs

---

src/plugin.json

After upgrading dependencies in https://github.com/grafana/synthetic-monitoring-app/pull/815 there are some incompatibilities with older versions of grafana (for instance, the `Stack` component is only available in `11.0.0`) so we need to update this configuration.

fix: change grafana dependency to 11.0.0

---

src/schemas/forms/ProbeSchema.ts

There was a bug in the validation of the custom probes longitude field which marked invalid values that were ok. This PR fixes that.
Fixes https://github.com/grafana/support-escalations/issues/11171

fix: custom probe longitude validation

---

package.json
src/scenes/Common/alertAnnotations.ts
yarn.lock

Upgrades scenes to the latest version (`5.1.0`)
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/825
Note: there was a breaking change where `SceneDataLayers` was renamed to `SceneDataLayerSet` (https://github.com/grafana/scenes/pull/640)

chore: upgrade scenes to latest version

---

src/components/Card/Card.tsx
src/components/ChooseCheckType.tsx

I noticed in the [non-initialized pages improvements PR](https://github.com/grafana/synthetic-monitoring-app/pull/839) that cards without links are displaying the hover cursor incorrectly.
Remove the `cursor: pointer` from the unneeded places and add it to the `:after` pseudo element on the title link.

fix: cursor type on cards without links

---

src/components/ProgrammaticManagement.tsx
src/components/Routing.test.tsx
src/components/Routing.tsx
src/components/TerraformConfig/TerraformConfig.tsx
src/hooks/useAppInitializer.ts
src/page/AlertingWelcomePage.tsx
src/page/AppInitializer.tsx
src/page/ChecksWelcomePage.tsx
src/page/ConfigPage.tsx
src/page/ProbesWelcomePage.tsx
src/page/SubsectionWelcomePage.tsx
src/page/WelcomePage.tsx
src/scenes/Common/emptyScene.tsx

When the plugin is not initialized, we now display dedicated pages according to each route. 
Home
Checks
Probes
Alerts
Config
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/807

feat: improve non-initialized pages

---

src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/SCRIPTED/getTablePanelStyles.ts

When the URL of a check was too long, the dashboard for scripted and multihttp checks was displaying a horizontal scroll which made it hard to navigate. This PR fixes that.
https://github.com/grafana/synthetic-monitoring-app/assets/6271380/788058a7-9a6b-4e8d-aba2-608398a52190
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/833

fix: avoid horizontal scrolling on check's dashboard

---

src/page/NewProbe/NewProbe.test.tsx

Adds a regression test for the fix on longitude validation on creating new probes in https://github.com/grafana/synthetic-monitoring-app/pull/836

fix: regression for longitude validation fix

---

src/plugin.json

In order to support eventually loading the synthentic monitoring appn assets from a CDN, the plugin.json needs to list all nested plugins in the includes.

chore: Add datasource to includes

---

src/components/CheckTestResult.tsx
src/components/CheckTestResultsModal.tsx
src/hooks/useLogData.ts
src/utils.ts

Instant queries sometimes don't return log data when executing scripts that take a long time. In these cases it's better to use range queries. 
This PR changes the query used to fetch logs when testing ad-hoc checks to be of type `range`. Also, we were sending a fixed `end` value that didn't update to the current time on consecutive requests, staying always in the past. By removing the parameter in the request, it will default to the current `$now` value (https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-logs-within-a-range-of-time).
https://github.com/grafana/synthetic-monitoring-app/assets/6271380/7f067ccb-6989-4519-8b51-212c4f11fca5
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/832

fix: make loki query fetch range instead of instant logs

---

src/components/CheckForm/FormLayout/FormSidebar.tsx

Whilst I was writing the updated documentation for the check form redesign, I remembered we had previously had feedback about the form sidebar buttons not being very obvious they are clickable.
I've added an underline on hover/focus-visible psuedo states to make it clearer these are buttons which will navigate to each section.
**Hover state**
**Focus-visible state**

feat: add hover/focus-visible interaction to form sidebar buttons

---

src/components/AlertRuleForm.tsx
src/components/Routing.test.tsx
src/components/Routing.tsx
src/page/AlertingPage.test.tsx
src/page/AlertingPage.tsx
src/page/CheckRouter.test.tsx
src/page/CheckRouter.tsx
src/page/pageDefinitions.ts
src/scenes/Common/editButton.tsx

Users with the role of `viewer` should be more restricted in what they can do/click in the app. 
For `viewer` users, this PR:
- Disables "Edit check" button in dashboards page
- Redirects the edit page route to home
- Redirects the config page to home
- Disables the "Populate default alerts", "Reset default alert rules" and "Save alerts" buttons in Alerting
Fixes https://github.com/grafana/support-escalations/issues/11601

Restrict access to certain pages/actions when user is Viewer

---

src/hooks/useUsageCalc.ts
src/utils.ts

When we have a new check type in development (like browser checks) and we create one of those checks, when we go to a branch which doesn't support those checks the check list page errors out and becomes unusable.
Fix the logic so that the check card still renders so the checks list page is still usable.

Render unknown check types in the checks list page

---

package.json
src/components/CheckList/CheckList.test.tsx
src/page/AlertingPage.test.tsx
src/page/ChecksPage.test.tsx
src/page/__testHelpers__/checkForm.tsx

With the new CheckForm testing meta framework which added significantly to our testing coverage and by extension our testing overhead, we were starting to see increasingly flaky tests in the CI/CD pipelines as well as when running them locally (I had recently resorted to getting a fan to cool my laptop when running them as it was heating up significantly...).
Our testing approach is 100% the correct way we should be doing testing so we shouldn't shy away from writing long-running integration tests as the alternatives are either:
1. moving the same tests to an e2e framework which can be equally (if not more so) flaky and will take magnitudes longer to run and get feedback. 
2. writing a ton of smaller unit tests that are often too closely coupled with the implementation and slow down …

Fix flaky tests

---

CHANGELOG.md

- Added datasource RBAC support in the plugin. The plugin now respects RBAC permissions for its datasources.
- Fix a bug with saving existing checks with empty TLS configs
- Fix a regression where the http checks follow redirects checkbox was missing

docs: update changelog for 1.14.12

---

src/page/NewCheck/__tests__/NewCheck.test.tsx
src/schemas/general/Job.ts

When checks contain single quotes or commas in their job names, it causes the queries executed by the panels to return no data. We should add a frontend validation in the job name field in order to prevent users to input these characters.
Fixes https://github.com/grafana/synthetic-monitoring-app/issues/900 
There have been several escalations related to this problem:
- https://github.com/grafana/support-escalations/issues/11944
- https://github.com/grafana/support-escalations/issues/6235
- https://github.com/grafana/synthetic-monitoring-app/issues/676

Prevent commas and quotes in job names

---

src/scenes/BROWSER/browserScene.ts
src/scenes/Common/AssertionsTable/AssertionsTable.tsx
src/scenes/SCRIPTED/scriptedScene.ts
src/scenes/utils.ts

The current Success Rate graph on the dashboards for MultiHTTP, Scripted, and Browser checks does not accurately display failure events. The issue arises because the query used for this visualization uses an interval that matches the frequency of the checks. This setup can leads to an incomplete visualization, as failures are nont captured effectively within the same interval.
**Problem**
The interval used in the query is equal to the check frequency, which can cause the graph to miss or inadequately represent failure events.
This results in a visualization that may not accurately reflect the true success rate, particularly in the presence of failures.
**Solution**
To improve the accuracy of the failure representation in the Success Rate graph, this PR modifies the interval to be a …

Fix success rate graph when showing failures

---

src/datasource/DataSource.ts
src/utils.ts

_Background context_
Synthetic Monitoring relies on two supporting databases to work at full capacity: a Grafana Cloud-hosted prometheus database and a Grafana Cloud-hosted Loki database.
A Grafana Cloud instance automatically provisions two datasource 'connectors' which connect to each respectively, confusingly referred to as a Prometheus **Datasource** and a Loki **Datasource**. In theory these should all remain stable, are named predictably and are immutable.
The problem which lies with the plugin is that it based on certain assumptions which may be untrue in certain situations (it is worth noting they are rare but do and will continue to exist and some clients specifically ask to bypass these assumptions):
- That the Synthetic Monitoring tenant is using the default set-up
- This …

fix: revert the way we do ds lookups

---

CHANGELOG.md

I'm bumping the changelog to do a release. Officially 1.14.12 went out but was quickly rolled back due to a critical bug. I am updating the changelog so this release is 1.14.13 with the same features and we are skipping publishing 1.14.12 officially.

Update changelog to 1.14.13

---

src/hooks/useDSPermission.ts
src/test/mocks/@grafana/runtime.tsx
src/test/utils.ts

In release 1.14.13 we added RBAC support across the SM plugin. This was intended as a halfway house before we added more pointed and fully-featured plugin RBAC support. Unfortunately we made a bad assumption about the default permissions each role is given.
When creating a Datasource an editor gets `datasource:read` by default and not `datasource:write`. The intent and explanations are documented in the [data source management](https://grafana.com/docs/grafana/latest/administration/data-source-management/) section of the Grafana docs.
For the time-being we are going to revert SM permissions to respect organisation roles rather than the access policies they have. This is how it worked prior to `1.14.13`.

fix: revert smwrite permissions to orgroles

---

src/page/DashboardPage.tsx
src/scenes/BROWSER/browserScene.ts
src/scenes/Common/uptimeStat.ts
src/scenes/DNS/dnsScene.ts
src/scenes/GRPC/getGRPCScene.ts
src/scenes/HTTP/httpScene.ts
src/scenes/PING/pingScene.ts
src/scenes/SCRIPTED/scriptedScene.ts
src/scenes/TCP/getTcpScene.ts
src/types.ts

This PR fixes the query that is used to calculate the uptime stat panel for each check. As described in this [escalation](https://github.com/grafana/support-escalations/issues/11197), this panel was displaying a value of `100%` even when the probes had 100% errors reaching the target.
**Which issue(s) this PR fixes**: 
Part of https://github.com/grafana/support-escalations/issues/11197. This solution addresses the first problem described here https://github.com/grafana/support-escalations/issues/11197#issuecomment-2195657543

fix: change query for uptime stat panel

---

src/components/ChooseCheckGroup.test.tsx
src/hooks/useCheckTypeGroupOptions.tsx

The gRPC shortcut label was showing on the check group cards when the gRPC feature flag was off.
Alter the logic in the `useCheckTypeGroupOptions` so that it is filtering protocols that have a featureToggle value.
There is a slight downside to this solution that we now have two places to update when we remove / change the status of feature flags however this should be mitigated by the additional and updated tests I've added.
[
Slack thread where it was discovered.](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1724344339996369)

fix: hide grpc option in check cards when feature flag off

---

src/components/CheckEditor/ProbeOptions.tsx
src/components/FeatureFlag.tsx
src/components/ProbeEditor/ProbeEditor.test.tsx
src/components/ProbeEditor/ProbeEditor.tsx
src/page/NewProbe/NewProbe.test.tsx
src/page/NewProbe/NewProbe.tsx
src/schemas/forms/ProbeSchema.ts
src/test/fixtures/probes.ts
src/test/utils.ts
src/types.ts

This PR addresses the UI changes needed in order to limit probe locations for browser checks. In particular:
- Adds disable browser checks checkbox in probe creation form (default false, and under the browser checks FF)
- Restricts available probes for browser checks based on capabilities
**Custom probe creation form**
**Only Oregon and Paris public probes are enabled for Browser Checks:**
Part of https://github.com/grafana/synthetic-monitoring/issues/116

feat: allow to disable browser checks in probe creation

---

src/page/NewCheck/__tests__/BrowserChecks/Scripted/1-script.ui.test.tsx
src/schemas/forms/script/parser.ts
src/schemas/forms/script/validation.ts

After a review session with @roobre, she gave me a heads up that the browser script options must be configured to use `chromium`, otherwise it will fail.
In this PR I improve the validation to make sure that it is correctly set.
Part of https://github.com/grafana/synthetic-monitoring-app/issues/864
Examples:
- `type` property missing
- `type` property set to firefox
- `type` property correctly set

feat: add validation to make sure browser type is chromium

---

src/components/CheckEditor/FormComponents/CheckStatusBadge.tsx
src/components/CheckEditor/FormComponents/ChooseCheckType.tsx
src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayout/FormSection.tsx
src/components/CheckUsage.tsx
src/components/ChooseCheckGroup.tsx
src/components/Toggletip/Toggletip.tsx
src/hooks/useCheckTypeGroupOptions.tsx
src/hooks/useCheckTypeOptions.ts

Because we are on a tight schedule I thought I'd make some of the change suggestions I had for the original branch (if we didn't have a hard deadline I'd have been more polite 😅)
I'll add the explanations for the changes in a self-review of the PR.

feat: updated status badge appearance and organisation

---

src/scenes/BROWSER/WebVitals/WebVitalGauge.tsx
src/scenes/BROWSER/WebVitals/cumulativeLayoutShift.ts
src/scenes/BROWSER/WebVitals/webVitalGaugeScene.tsx
src/scenes/BROWSER/WebVitals/webVitalsTable.ts
src/scenes/ExplorablePanel.ts

Improvements to the browser checks dashboard:
- Adds explore links in web vitals panels so users can see how the number is calculated by getting access to the query in Explore.
- Removes the unit in the CLS column of the web vitals by url table
Part of https://github.com/grafana/synthetic-monitoring-app/issues/866
Addresses https://github.com/grafana/synthetic-monitoring-app/pull/918#pullrequestreview-2297156876

Browser checks dashboard - Iteration 3

---

src/components/CheckEditor/FormComponents/CheckStatusBadge.tsx
src/components/CheckEditor/FormComponents/ChooseCheckType.tsx
src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayout/FormSection.tsx
src/components/CheckUsage.tsx
src/components/ChooseCheckGroup.tsx
src/components/Toggletip/Toggletip.tsx
src/hooks/useCheckTypeGroupOptions.tsx
src/hooks/useCheckTypeOptions.ts
src/types.ts

- Adds a private preview badge to the browser checks option in the Check Creation view
- Adds banner on the create/edit form for Browser Checks indicating usage is free for private preview.
Closes https://github.com/grafana/synthetic-monitoring/issues/146

feat: add private preview badge to browser checks

---

package.json
yarn.lock

The agent is using `0.53.0` so let's update the k6 types version used in the frontend to match that version.

chore: upgrade k6 types version to 0.53.0

---

src/components/CheckEditor/ProbeOptions.tsx

Setting the min frequency of Browser Checks to 60 seconds, same as Scripted and Multihttp checks.

fix: set browser checks min frequency

---

src/components/BrowserExamplesMenu/constants.ts
src/components/BrowserExamplesMenu/snippets/colorscheme.js
src/components/BrowserExamplesMenu/snippets/cookies.js
src/components/BrowserExamplesMenu/snippets/dispatch.js
src/components/BrowserExamplesMenu/snippets/evaluate.js
src/components/BrowserExamplesMenu/snippets/fillform.js
src/components/BrowserExamplesMenu/snippets/getattribute.js
src/components/BrowserExamplesMenu/snippets/keyboard.js
src/components/BrowserExamplesMenu/snippets/mouse.js
src/components/BrowserExamplesMenu/snippets/querying.js
src/components/BrowserExamplesMenu/snippets/touchscreen.js
src/components/BrowserExamplesMenu/snippets/waitForEvent.js
src/components/BrowserExamplesMenu/snippets/waitForFunction.js
src/components/CheckEditor/FormComponents/BrowserCheckScript.tsx
src/components/WelcomeTabs/constants.ts

Adds script examples to browser checks, taken from https://github.com/grafana/xk6-browser/tree/main/examples
Some of them were omitted as they include features we don't support yet, such as page screenshots.

feat: add script examples to browser checks

---

src/components/CheckEditor/FormComponents/HttpRequest.tsx
src/components/MultiHttp/MultiHttpCollapse.tsx

We've had reports that the way we are generating `data-fs-elements` is causing us to hit a limit in FullStory.
Remove two of the main offenders in the check creation flow:
1. The request headers data-fs-element attribute
2. The MultiHttpCollapse data-fs-element attribute

fix: remove dynamic and unused data-fs-element attributes

---

src/components/CheckForm/CheckForm.tsx
src/components/ChooseCheckGroup.tsx
src/components/PluginPage.tsx
src/components/Routing.tsx
src/contexts/SMDatasourceContext.tsx
src/page/AlertingPage.tsx
src/page/ConfigPage/ConfigPage.tsx
src/page/EditProbe/EditProbe.tsx
src/page/NewProbe/NewProbe.tsx
src/page/Probes/Probes.tsx
src/page/SubsectionWelcomePage.tsx
src/page/UnprovisionedSetup.tsx
src/page/WelcomePage.tsx
src/test/mocks/@grafana/runtime.tsx

- remove references to `topnav`
- `topnav` has been default enabled since v9.5
- we intend to remove the toggle soon™️ 
- removes the `PluginPage` wrapper in favour of using `PluginPage` directly from `@grafana/runtime`
Fixes #

Chore: Remove references to `topnav`

---

src/components/constants.ts
src/page/NewCheck/__tests__/BrowserChecks/Scripted/2-defineUptime.payload.test.tsx

Sets default browser checks timeout to 1 min.
Closes https://github.com/grafana/synthetic-monitoring-app/issues/943

feat: set default timeout for browser checks to 1 min

---

package.json
src/components/CheckEditor/transformations/toFormValues.browser.ts
src/components/CheckEditor/transformations/toFormValues.scripted.ts
src/components/CheckEditor/transformations/toPayload.browser.ts
src/components/CheckEditor/transformations/toPayload.scripted.ts
src/page/NewCheck/__tests__/BrowserChecks/Scripted/5-execution.payload.test.tsx
yarn.lock

Closes: [#910](https://github.com/grafana/synthetic-monitoring-agent/issues/910)
This pull request addresses an issue where forms containing Unicode characters were unable to save in both browser and scripted checks. The error encountered was:
```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```
The root of the problem lies in the native `btoa` and `atob` methods, which are designed to handle only ASCII characters. When Unicode characters—such as emojis—are present, these methods throw an error.
To resolve this issue, this PR replaces the use of `btoa` and `atob` with the `js-base64` library, which fully supports encoding and decoding of Unicode strings. This change ensures that our application can handle a …

Fix scripts encoding error

---

src/hooks/useCheckTypeOptions.ts

Changes browser checks to public preview status
We're also removing the public preview badge for scripted checks as they go GA.

chore: change browser checks to public preview status

---

src/page/NewCheck/__tests__/BrowserChecks/Scripted/1-script.ui.test.tsx
src/schemas/forms/script/parser.ts
src/schemas/forms/script/validation.ts

To prevent execution errors, we're adding some extra validations, in particular, these properties are not allowed in the `options` object:
- `duration`
- `vus` > 1
- `iterations` > 1

Feat: extra validations for browser checks

---

src/components/BrowserExamplesMenu/snippets/fillform.js

The browser squad now recommends using the async `check` polyfill in all code examples and has updated the `fillform` example in https://github.com/grafana/xk6-browser/tree/main/examples
In order to be consistent, the `fillform` example for synthetics browser checks has been updated as well.

chore: update fillform example to use async check

---

.drone.yml

Modifies the release process in order to be compatible with the usage of release-please and avoid some current manual steps.
Specifically:
- Removes the tag and release generation when promoting build to production, as that should now be done by release-please when merging the version PR.
- Modifies the configuration for the deployment tools PR when promoting to production so it is automatically merged (the same way it's done for staging) instead of requiring a manual approval from reviewers.
Updates https://github.com/grafana/synthetic-monitoring/issues/50.

chore: Tune release process

---

.drone.yml

After the change in the release process, the tag is now generated when the release PR is merged to main. At this point, there is a current trigger for a tag that tries to publish to gcom the released plugin. However, this step should not happen automatically on the tag generation but happen when promoting the release to production. Therefore, move this step as the last step for the promote->production event trigger.

chore: Fix release CI/CD

---

scripts/publish-gcom.sh

Fixes the version parsing from publish-gcom.sh script. Since there is no longer a tag Drone pipeline, the variable DRONE_TAG is not set when promoting to production from the push pipeline. Therefore obtain the version from the package.json file.

chore: Fix publish version

---

.drone.yml

Installs git as a requirement before publishing the plugin when promoting to production.

chore: Add git to publish step

---

.drone.yml
scripts/install-ci-deps-apt.sh

Changes the image used for the publish step to ubuntu:latest, so the
CI dependencies script can install the required packages. Since
we are now not using the curl Docker image for this step, curl must be
added to the list of dependencies.

chore: Change publish step image

---

scripts/publish-gcom.sh

A space before the bash bang was making it being executed through sh in ubuntu:latest as part of the promote production CI pipeline, on which an option set in the script is not supported. Remove the extra space so the sript is executed in bash and 'set -eufo pipefile' is applied correctly.

fix: Publish script

---

src/components/CheckList/CheckList.tsx

We had a [bug reported internally in Slack](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1727773255480849) that our reachability Asc / Desc. were reporting the wrong way round.
This PR switches the order of Asc / Desc. As I was fixing this I noticed that undefined and other falsey values of reachability were given a value of 101 so put them above 100% (which I think is what led to this bug implementation in the first place).
I noticed as I was fixing it that the code could be much more performant and use less CPU cycles, too 😄 
**Before**
**After**

Fix: Update asc / desc reachability sorting

---

src/components/BrowserExamplesMenu/snippets/colorscheme.js
src/components/BrowserExamplesMenu/snippets/cookies.js
src/components/BrowserExamplesMenu/snippets/dispatch.js
src/components/BrowserExamplesMenu/snippets/evaluate.js
src/components/BrowserExamplesMenu/snippets/getattribute.js
src/components/BrowserExamplesMenu/snippets/querying.js
src/components/BrowserExamplesMenu/snippets/waitForFunction.js
src/components/constants.ts

Updates browser checks examples to use `async check` from `https://jslib.k6.io/k6-utils/1.5.0/index.js` as recommended in the [FAQ document](https://docs.google.com/document/d/1SbBdhYVGnEQ9XJe6DKYMErPI3O_E3anAp3Hdu_faUo8/edit#heading=h.duuadjcekgl6)

fix: update browser examples to use async check

---

src/checkUsageCalc.test.ts
src/checkUsageCalc.ts

Closes https://github.com/grafana/synthetic-monitoring-app/issues/983
We were previously calculating the number of check usages for MultiHTTP checks incorrectly by not considering the number of probe locations. This PR fixes this calculation. Additionally, tests have been added to ensure the calculation works as expected moving forward.

Fix check usage calculation for MultiHTTP checks

---

src/components/CheckEditor/CheckProbes/ProbesList.tsx

Fixes the color of the column header probe selector for the Light theme.
Light theme
Dark theme

fix: probe selector column header color

---

src/components/constants.ts

This PR updates the default scripted check example to add use of the `fail()` function, and explains why you would use it. 
Many people assume that if a `check()` does not pass,  the test run will fail and this will impact reachability and uptime.  They are unaware of the `fail()` function and why they should use it. 
This makes the default script longer, but it is still short enough that it fits on a typical laptop screen:

Update scripted check default example/snippet

---

src/hooks/useMonthlyTotalExecutionCount.test.ts
src/hooks/useMonthlyTotalExecutionCount.ts

Addresses the FE portion of: https://github.com/grafana/support-escalations/issues/13498
We aren't filtering out disabled checks when calculating a user's execution count.
Add a filter to remove disabled checks when checking monthly execution counts.

fix: filter out disabled checks for execution count total

---

CODEOWNERS

CHANGELOG.md, package.json and
.github/release-please/release-please-config.json are updated as part of creating a release. In order to allow anybody in the team to run that process, add synthetic-monitoring-dev as owners of those files.
Fixes #

fix: add synthetic-monitoring-dev as owners of release files

---

src/scenes/BROWSER/WebVitals/cumulativeLayoutShift.ts
src/scenes/BROWSER/WebVitals/inputResponseTime.ts
src/scenes/BROWSER/WebVitals/pageLoad.ts
src/scenes/BROWSER/WebVitals/webVitals.ts
src/scenes/BROWSER/WebVitals/webVitalsTable.ts
src/scenes/BROWSER/dataTransferred.ts
src/scenes/Common/AssertionsTable/AssertionsTable.tsx
src/scenes/Common/AssertionsTable/successOverTimeByProbe.ts
src/scenes/Common/uptimeStat.ts
src/scenes/SCRIPTED/ResultsByTargetTable/durationByTargetProbe.ts
src/scenes/SCRIPTED/ResultsByTargetTable/errorRateByTargetProbe.ts
src/scenes/SCRIPTED/ResultsByTargetTable/resultsByTargetTableQueries.ts
src/scenes/SCRIPTED/dataTransferred.ts

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1029
The data transferred and assertions panels in the Browser and Scripted dashboards aren't taking into account filtered probes. This PR fixes that. 
Since in dev we only have one running probe location, I've validated the queries work as expected using Explorer in my prod account:
**Before setting the probe filter (as it currently works in the dashboards):**
Data sent chart:
Data received chart:
Success rate chart:
**After setting the probe filter (after this PR implementation):**
Data sent chart:
Data received chart:
Success rate chart:

fix: filter by probe on data transferred and assertions panels for browser and scripted checks

---

src/components/CheckEditor/transformations/toFormValues.alerts.ts
src/components/CheckEditor/transformations/toPayload.alerts.ts
src/datasource/__mocks__/checkAlerts.ts
src/test/fixtures/checkAlerts.ts
src/types.ts

The API is removing the id property for check alerts in https://github.com/grafana/synthetic-monitoring-api/pull/1115 as they can be identified just by their name. 
Updating the frontend code accordingly.

chore: remove checkAlert id concept

---

src/page/CheckList/components/CheckItemActionButtons.tsx
src/page/CheckList/components/CheckListItemCard.tsx
src/page/CheckList/components/CheckListItemDetails.tsx

Closes #1042 
With a large number of labels, the View Dashboard, Edit and Delete buttons get overlapped. This PR fixes it by wrapping them.
https://github.com/user-attachments/assets/ba9afe55-6a18-4209-bf74-a2d4ae102537

fix: wrap labels to always display View dashboard button

---

src/components/CheckForm/CheckForm.constants.tsx
src/components/CheckForm/FormLayouts/CheckBrowserLayout.tsx
src/components/CheckForm/FormLayouts/CheckDNSLayout.tsx
src/components/CheckForm/FormLayouts/CheckGrpcLayout.tsx
src/components/CheckForm/FormLayouts/CheckHttpLayout.tsx
src/components/CheckForm/FormLayouts/CheckMultiHttpLayout.tsx
src/components/CheckForm/FormLayouts/CheckPingLayout.tsx
src/components/CheckForm/FormLayouts/CheckScriptedLayout.tsx
src/components/CheckForm/FormLayouts/CheckTCPLayout.tsx
src/components/CheckForm/FormLayouts/CheckTracerouteLayout.tsx
src/components/TimeSlider/styles.ts
src/page/NewCheck/__tests__/BrowserChecks/Scripted/5-execution.payload.test.tsx
src/page/NewCheck/__tests__/MultiStepChecks/MultiHTTP/5-execution.payload.test.tsx
src/page/NewCheck/__tests__/NewCheck.journey.test.tsx
src/page/NewCheck/__tests__/ScriptedChecks/Scripted/5-execution.payload.test.tsx
src/schemas/forms/BaseCheckSchema.ts

Closes #1048 
- Allows a timeout of 90 seconds for `browser`, `scripted` and `multihttp` checks
- Adds validation to prevent frequency lower than the chosen timeout
- Adds tests
https://github.com/user-attachments/assets/bc15e366-6940-406c-b366-343a3bed43dc

Feat: increase check timeout to scripted, browser and multihttp checks

---

.github/workflows/ci.yml

Keeping ci.yml but stripped it back. Need to migrate away from Drone in the near future.

fix: strip back ci.yml checks

---

src/components/CheckEditor/CheckProbes/CheckProbes.tsx
src/data/useProbes.ts
src/page/Probes/Probes.tsx
src/utils.test.ts
src/utils.ts

Currently, the probe list can be a little difficult to find the probe you after when searching through the list. The probes come back in ID order which is different per region that a user's stack is located in.
The second issue is that the probe names are in pascal case, which isn't so intuitive and familiar for a user to find when using the probe search. 
1. Sort the probes alphabetically in `useProbesWithMetadata`
2. Change the name to utilize the display name
3. Alphabetize the region in the check probes display
**Before**
**After**

feat: sort probes alphabetically

---

src/components/CheckEditor/CheckProbes/CheckProbes.tsx
src/components/CheckEditor/CheckProbes/ProbesFilter.tsx
src/components/CheckEditor/CheckProbes/ProbesList.tsx
src/components/CheckEditor/ProbeOptions.tsx
src/components/CheckEditor/ProbesMetadata.ts
src/components/DeleteProbeButton/DeleteProbeButton.tsx
src/components/DeleteProbeButton/DeleteProbeButton.utils.ts
src/components/ProbeCard/ProbeCard.test.tsx
src/components/ProbeCard/ProbeCard.tsx
src/components/ProbeCard/ProbeStatus.tsx
src/data/useProbes.ts
src/page/CheckList/CheckList.test.tsx
src/page/CheckList/CheckList.tsx
src/page/CheckList/CheckList.utils.ts
src/page/CheckList/components/BulkActionsModal.test.tsx
src/page/CheckList/components/CheckFilters.tsx
src/page/EditProbe/EditProbe.test.tsx
src/page/EditProbe/EditProbe.utils.tsx
src/page/NewCheck/__tests__/NewCheck.journey.test.tsx
src/page/NewProbe/NewProbe.tsx
src/page/Probes/Probes.test.tsx
src/page/__testHelpers__/apiEndPoint.ts
src/page/__testHelpers__/multiStep.ts
src/page/__testHelpers__/scripted.ts
src/test/utils.ts
src/types.ts

Introduced a small regression in https://github.com/grafana/synthetic-monitoring-app/pull/1050. Naively mutated the `name` attribute in the probes rather than add an additional field. This caused the linking to the checks list with a probe filter to break.
In the interest of keeping backwards compatibility, I've made the displayName field additive rather than mutate the name field. I've added a test for the probe filter (it was the only filter type missing a test 😅 ) on the Checks List page so it doesn't regress again.
I've also gone through and adapted the types so they are more accurate, adding a `ProbeWithMetadata` type after it gets mapped onto.

fix: add displayName on top of name rather than replace

---

.drone.yml

As part of https://github.com/grafana/deployment_tools/issues/197258, we are replacing `updater` image references using GCR to now use GAR. GCR is deprecated and the `updater` image that lives there is no longer being updated.
See: https://github.com/grafana/deployment_tools/issues/197240

fix: pull updater image from gar instead of gcr

---

src/scenes/BROWSER/WebVitals/webVitalGaugeScene.tsx

Fixes the web vitals components as they were displaying 0.0 instead of the reduced data series value. This happened because we were relying on the `refId` of the series in order to obtain its value, but this value has been changed recently and it broke our implementation. Since there’s only one series per query, I simplified the implementation to directly access the first series, removing the need for `refId` filtering.
Closes https://github.com/grafana/support-escalations/issues/14520
Before
After
Notes:
The `refId` value from the data series changed to return a prefix of the transformation applied to it (`reduce` in our case): 
which the current app code wasn't expecting:

fix: get web vitals value for gauge component

---

src/components/CheckForm/CheckForm.constants.tsx
src/page/NewCheck/__tests__/BrowserChecks/Scripted/5-execution.payload.test.tsx
src/page/NewCheck/__tests__/MultiStepChecks/MultiHTTP/5-execution.payload.test.tsx
src/page/NewCheck/__tests__/NewCheck.journey.test.tsx
src/page/NewCheck/__tests__/ScriptedChecks/Scripted/5-execution.payload.test.tsx

Related to https://github.com/grafana/synthetic-monitoring-app/issues/1048
Allows a timeout of 120 seconds for `browser`, `scripted` and `multihttp` checks.

feat: change browser, scripted and multihttp timeouts up to 120s

---

src/components/CheckEditor/ProbesMetadata.ts
src/data/useProbes.ts
src/page/CheckList/CheckList.hooks.ts
src/page/CheckList/CheckList.test.tsx
src/page/CheckList/CheckList.tsx
src/test/utils.ts
src/types.ts
src/utils.test.ts
src/utils.ts

We had a bug where you couldn't filter most probes correctly on the check list page. We were made aware of it in this escalation: https://github.com/grafana/support-escalations/issues/14671
We had unit and integration tests covering this problem but none that were comprehensive enough to catch the bug.
Whilst fixing this bug I discovered the reset button also wasn't working so put in a quick fix.
I've added the `displayName` property to our hard-coded probe meta data list. Upon reflection this is the safer way to handle this problem as it no longer transforms private probe names, which would likely want to restrict their display to the user-inputted name.
Regardless, I've updated `camelCaseToSentence` to `pascalCaseToSentence`. It ensures that if the first letter is a capital it doesn't …

fix: probe filtering behaviour and reset button

---

src/components/CheckForm/checkForm.hooks.ts
src/page/NewCheck/__tests__/ApiEndPointChecks/CommonFields.payload.test.tsx

Prevents executing the new alerts `POST` request to update alerts when saving a check if the feature flag is off.
This was a regression introduced after a refactor PR. Before, we were relying on the absence of the `alerts` property from the form in order to save them or not. Since after the refactor the `alerts` prop is always present, I'm now relying on the status of the feature flag directly.
Ref https://raintank-corp.slack.com/archives/C0162C1K9E1/p1739894967044089

fix: prevent submitting alerts per check when FF is off

---

src/page/CheckList/components/BulkActionsModal.test.tsx
src/page/CheckList/components/BulkActionsModal.tsx

Fixes a wrong behavior when bulk-editing checks that ended up adding duplicated probe locations to the check.
https://github.com/user-attachments/assets/edf1deba-94d3-4319-b1a7-ccfa7b4a62d2
Closes https://github.com/grafana/synthetic-monitoring-app/issues/1071

fix: prevent adding duplicated probes when bulk editing

---

src/components/TerraformConfig/terraformConfigUtils.ts
src/components/TerraformConfig/terraformTypes.ts
src/hooks/useTerraformConfig.test.tsx
src/test/fixtures/terraform.ts

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1033, https://github.com/grafana/synthetic-monitoring-app/issues/1028, https://github.com/grafana/synthetic-monitoring-app/issues/1032.
Fixes the export code for terraform to address:
- Adjust check capabilities format
- Include check frequency and timeout
- Omit dns validate fields when empty.

Fix: terraform export fixes

---

src/scenes/Common/AssertionsTable/AssertionsTable.tsx

When https://github.com/grafana/xk6-sm/pull/34 is merged, it will be possible for `check result` logs to have fractional values, if the same check name is used twice. For example, the following snippet:
```js
check(res, {
'is 200': () => true,
}
);
check(res, {
'is 200': () => false,
}
);
```
Currently yields:
```
time="2025-01-14T17:32:54+01:00" level=info msg="check result" check="is 200" metric=checks_total scenario=default source=sm value=1
time="2025-01-14T17:32:55+01:00" level=info msg="check result" check="is 200" metric=checks_total scenario=default source=sm value=0
```
After https://github.com/grafana/xk6-sm/pull/34 is merged, it will yield
```
time="2025-01-14T17:32:54+01:00" level=info msg="check result" check="is 200" …
```

fix: handle fractional "check result" logs

---

src/scenes/BROWSER/browserScene.ts
src/scenes/Common/editButton.tsx
src/scenes/DNS/dnsScene.ts
src/scenes/GRPC/getGRPCScene.ts
src/scenes/HTTP/httpScene.ts
src/scenes/PING/pingScene.ts
src/scenes/SCRIPTED/scriptedScene.ts
src/scenes/TCP/getTcpScene.ts
src/scenes/Traceroute/getTracerouteScene.ts

**Before**
**After**
When an `instance` value includes a comma, we cannot enable the "Edit Check" button on the dashboard page for an affected check. The reason is that we take the `job` and `target|instance` value from the check object (which includes the `id`), then parse both values with `CustomVariable`, then use the parsed values to find an item in an array, that matches `job` and `target|instace`, to get the `id`
This PR takes the `id` directly and uses the `id` to create the route for the Edit Button
Resolves [1090](https://github.com/grafana/synthetic-monitoring-app/issues/1090)
Fixes #

fix: edit check button disabled issue

---

package.json
src/components/CodeEditor/k6.types.ts
yarn.lock

Bumps k6 types. To have the correct types for the current k6 version

chore: bump k6 typings to v0.57.1

---

.drone.yml

Changes the drone signature so that builds don't need to be manually approved.
It's been changed by running `./scripts/drone-sign.sh`

fix: update drone signature to prevent having to manually approve builds

---

src/components/CheckForm/AlertsPerCheck/AlertItem.tsx
src/components/CheckForm/AlertsPerCheck/AlertsPerCheck.constants.tsx
src/components/CheckForm/AlertsPerCheck/TLSTargetCertificateCloseToExpiringAlert.tsx
src/datasource/__mocks__/checkAlerts.ts
src/page/NewCheck/__tests__/ApiEndPointChecks/HTTPCheck/4-alerting.payload.test.tsx
src/schemas/general/CheckAlerts.ts
src/test/fixtures/checkAlerts.ts
src/types.ts

The underlying metric for the alert rule is the same for multiple check types (HTTP, gRPC, TCP), therefore, since the alert can be reused for these types, replace the 'HTTP' prefix, which referenced the check type, for 'TLS'.
Related grafana/synthetic-monitoring-api/pull/1300

feat: rename the TLS certificate expiry alert

---

src/components/TerraformConfig/terraformConfigUtils.ts
src/components/TerraformConfig/terraformMultiHTTPConfigUtils.ts
src/components/TerraformConfig/terraformTypes.ts
src/hooks/useTerraformConfig.test.tsx

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1094
Closes https://github.com/grafana/synthetic-monitoring-app/issues/853
This PR introduces a refactoring of the Terraform configuration generation, specifically focusing on `MultiHTTP` and `Scripted`/`Browser` checks to match the terraform provider expected structure, as these kind of checks are failing when trying to import them.
The changes include:
1. Extraction of `MultiHTTP-specific` logic into a dedicated utility file
2. Improved type safety and validation for assertions and variables
3. Addition of scripted and browser check support
4. Enhanced test coverage
- Created new file `terraformMultiHTTPConfigUtils.ts` to handle MultiHTTP-specific transformations, as MultiHTTP checks can be complex due to their nested …

Fix: Terraform fixes for scripted, browser and multiHTTP checks

---

yarn.lock

Recreated yarn.lock to remove old resolutions
This PR addresses the SLO [alert](https://ops.grafana-ops.net/a/grafana-vulnerabilityobs-app/projects/sources/36/version/16046?var-cve=&var-pkg=) for path-to-regexp 1.8.0 by recreating the yarn.lock file. 
The old version was a transient dependency that has been upgraded to the latest version.

fix: recreate yarn.lock to upgrade dependencies

---

src/components/CheckEditor/FormComponents/MultiHttpCheckRequests.tsx
src/components/CheckEditor/FormComponents/RequestBodyTextArea.tsx
src/components/CheckEditor/FormComponents/RequestHeaders.tsx
src/components/CheckEditor/FormComponents/RequestQueryParams.tsx
src/components/CheckForm/CheckForm.tsx
src/components/CheckForm/FormLayout/FormLayout.tsx
src/components/NameValueInput/NameValueInput.tsx
src/components/Request/RequestOptions.tsx
src/datasource/QueryEditor.tsx
src/page/CheckList/components/CheckFilters.tsx
yarn.lock

After recreating the `yarn.lock` file (https://github.com/grafana/synthetic-monitoring-app/pull/1105) we got some typing errors mainly related to React Hook Form upgrading from 7.51.5 to 7.55.0. This PR fixes them.

fix: typing errors after upgrading dependencies

---

.gitignore

Adding the cursor files to the `.gitignore` file so we can experiment locally what works for us best if using Cursor.

chore: add cursor files to gitignore

---

src/components/CheckForm/checkForm.hooks.ts
src/components/ProbeEditor/ProbeEditor.tsx
src/schemas/forms/BaseCheckSchema.ts
src/schemas/forms/BrowserCheckSchema.ts
src/schemas/forms/DNSCheckSchema.ts
src/schemas/forms/GRPCCheckSchema.ts
src/schemas/forms/HttpCheckSchema.ts
src/schemas/forms/MultiHttpCheckSchema.ts
src/schemas/forms/PingCheckSchema.ts
src/schemas/forms/ProbeSchema.ts
src/schemas/forms/ScriptedCheckSchema.ts
src/schemas/forms/TCPCheckSchema.ts
src/schemas/forms/TracerouteCheckSchema.ts
src/schemas/general/CheckAlerts.ts
src/schemas/general/CheckProbes.ts
src/schemas/general/DomainNameTarget.ts
src/schemas/general/Frequency.ts
src/schemas/general/Header.ts
src/schemas/general/HostNameTarget.ts
src/schemas/general/HostPortTarget.ts
src/schemas/general/HttpTarget.ts
src/schemas/general/Job.ts
src/schemas/general/Label.ts
src/schemas/general/Probes.ts
src/schemas/general/QueryParam.ts
src/schemas/general/TLSConfig.ts
src/schemas/general/Target.ts

We were using PascalCase schema names across the codebase, as the [zod author recommends](https://github.com/colinhacks/zod/pull/3285#issuecomment-1998639354). Upon reflection we have decided PascalCase is not a suitable naming convention as @w1kman explains:
> A schema is not a typescript type, nor is it a class constructor.
You "cannot" export Dog twice, so instead pretending that Dog is a type (when it is a schema) and making up a new name for the actual type (DogType or the schema), you could actually make sense of the exports.
import { Dog } from 'schemas'  <- importing a type
import { dog } from 'schemas' <- importing a schema
Also this
"But for utility schemas with a self-evident static type I wouldn't capitalize."
Feelings, not rules
The author of the PR is following common …

chore: renamed all schemas to camelcase

---

src/components/CheckForm/useCheckType.tsx
src/components/SceneRedirecter.tsx
src/hooks/useQueryParametersState.ts
src/hooks/useSearchParams.ts
src/hooks/useURLSearchParams.ts
src/routing/InitialisedRouter.tsx

Since we introduced `react-query` this annoyed me. Today was the day it needed renaming.

chore: rename useQuery hook to useURLSearchParams

---

.github/release-please/release-please-config.json

Fixes the release-please commit message in order to comply with the repository configuration which requires commit messages to match the regex:
```
(feat|fix|chore|docs): .+
```

chore: fix release-please commit message format

---

src/faro.ts
src/scenes/SCRIPTED/ResultsByTargetTable/ResultByTargetTable.tsx
src/scenes/SCRIPTED/ResultsByTargetTable/resultsByTargetTableQueries.ts
src/scenes/SCRIPTED/ResultsByTargetTable/utils.ts

This PR standardizes enum naming to follow PascalCase convention.
Changes:
- Rename `RESULTS_BY_TARGET_TABLE_REF_ID` to `ResultsByTargetTableRefId`
- Rename `FARO_ENV` to `FaroEnv`
- Update all references to use the new enum names
This change is part of our ongoing effort to maintain consistent naming conventions across the codebase.

chore: standardize enum naming to PascalCase

---

src/hooks/useCheckTypeOptions.ts

chore: remove public preview badge for Browser checks GA

---

src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretEditModal.test.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretEditModal.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretsManagementUI.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/secretSchema.test.ts
src/page/ConfigPageLayout/tabs/SecretsManagementTab/secretSchema.ts

**What this PR does / why we need it**: Adds name uniqueness to client validation
**Which issue(s) this PR fixes**: #1136
**How to test**:
1. Create a secret with the name my-secret, save.
2. Create another secret with the same name (my-secret)
3. Notice how it looks like everything went OK, but no secret was saved.

fix: add existing secret names to client validation

---

src/data/useCheckAlerts.ts
src/datasource/DataSource.ts
src/test/handlers/alerts.ts

After a conversation with @ka3de, we agreed the response for the `PUT /check/:id/alerts` endpoint should not return the list of alerts in the response body, as this is consumed from the `GET` endpoint already.
This PR addresses the frontend portion of the changes, while it is also going to be removed on the API side.

fix: update return type of update alerts PUT request

---

src/scenes/BROWSER/WebVitals/webVitalGaugeScene.tsx
src/scenes/ExplorablePanel.ts
src/scenes/HTTP/HttpDashboard.tsx
src/scenes/HTTP/useVizPanelMenu.tsx
src/scenes/utils.test.ts
src/scenes/utils.ts

Addresses: https://github.com/grafana/synthetic-monitoring-app/issues/1141
1. The probe variable shows unrelated probes
2. When selecting multiple values for probes they don't get parsed when opened up in Explore correctly, instead of `probe=~"probe1|probe2"` we receive `probe=~"{probe1,probe2}"` which is incorrect.
For HTTP dashboards we use React scenes and use `useVariableInterpolator` to generate the Explore query and for all the other dashboards we use vanilla scenes so use `sceneGraph.interpolate`.
Following the code in scenes we end up at `sceneInterpolator` and `formatRegistry` and it is difficult to discern if and how we pass a custom format for the variable. For the time-being I have created `correctSceneVariableInterpolation` to wrap the interpolate function and added the …

fix: added correctSceneVariableInterpolation function with tests

---

src/components/TerraformConfig/terraformTypes.ts
src/hooks/useTerraformConfig.test.tsx
src/hooks/useTerraformConfig.ts
src/page/ConfigPageLayout/tabs/TerraformTab.tsx

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1128
This PR introduces support for exporting and importing Synthetic Monitoring check alerts as Terraform resources and commands. The changes allow users to manage per-check alert configurations via Terraform, improving automation and reproducibility for alerting setups.
**1. Terraform Import Commands for Check Alerts**
New import commands for `grafana_synthetic_monitoring_check_alerts` are generated and displayed in the Config page.
Only checks with defined alerts will have corresponding import commands.
The Config page now includes a dedicated section to copy these commands for easy use.
**2. Exported Terraform Config for Check Alerts**
The exported Terraform config now includes a …

Feat: add terraform config for Per-check alerts

---

src/components/AlertStatus/AlertStatus.tsx
src/components/CheckEditor/transformations/toFormValues.http.ts
src/components/CheckEditor/transformations/toFormValues.utils.ts
src/components/CheckForm/checkForm.hooks.ts
src/data/useGMAlerts.ts
src/hooks/useAlertRules.ts
src/hooks/useTerraformConfig.test.tsx
src/hooks/useTerraformConfig.ts
src/test/db.ts
src/test/fixtures/checks.ts
src/types.ts

Fixes the case for alerts field as included in the list checks endpoint response.
Related grafana/synthetic-monitoring-api/pull/1387

fix: Fix list check alerts case

---

src/components/AlertStatus/AlertStatus.tsx
src/components/AlertStatus/GrafanaNamespaceAlertRuleDisplay.tsx
src/components/AlertStatus/NotOkStatusInfo.tsx
src/components/AlertStatus/PerCheckAlertsGroups.tsx
src/components/CheckEditor/transformations/toFormValues.alerts.ts
src/components/CheckForm/AlertsPerCheck/AlertItem.test.tsx
src/components/CheckForm/AlertsPerCheck/AlertItem.tsx
src/data/useGMAlerts.test.ts
src/data/useGMAlerts.ts
src/datasource/__mocks__/checkAlerts.ts
src/test/db.ts
src/test/fixtures/alerting.ts
src/test/fixtures/checkAlerts.ts
src/test/fixtures/checks.ts
src/types.ts

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1131
With the new per-check alerts, the creation request can be successful but there can still be asynchronous errors that need to be displayed to the user. This PR addresses this requirement. 
From https://github.com/grafana/synthetic-monitoring/issues/266:
>Alert rules creation process is performed asynchronously from the HTTP request that triggers its creation. This means that the user might have received a successful response (202 HTTP Accepted), but the rule itself might not end up being created (for example due to quota limits or other possible errors).
>The backend registers the possible errors returned from Hosted Grafana. We should expose these errors to the plugin, so the plugin can take different actions in order …

feat: add indicator when there is an error with per-check alerts

---

eslint.config.mjs

1. Meant to do this a while ago when I discovered that webpack strips console log statements when compiling
2. Excuse to trigger CI/CD

chore: remove unnecessary console eslint rule

---

src/components/Gauges/Gauge.tsx
src/components/Gauges/SuccessRateGaugeProbe.tsx
src/components/ProbeCard/ProbeCard.tsx
src/components/ProbeStatus/ProbeStatus.tsx
src/components/constants.ts

For probe-related components, the reachability description we are currently displaying can be confusing (see this [Slack](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1750087772831939) conversation):
> The reachability info popup states "The success rate of all the probes. Reachability decreases when any probe fails.", which is a little misleading when viewed in context of the probe list. "The success rate of all synthetic checks run by this probe" might be a little more clear, since the language implies the probe is failing and not the checks.
In this PR, I made the following changes:
- Added a new `PROBE_REACHABILITY_DESCRIPTION` constant with the wording "The success rate of all synthetic checks run by this probe."
- Updated the probe-related components (ProbeCard, …

fix: change reachability description for probes view

---

.github/workflows/call_update-deployment-tools.yml
.github/workflows/dispatch_deploy-plugin.yml
.github/workflows/on-push-to-main.yml

**Changes GAR authentication job to prevent logging an error**
The `login-to-gar` shared action was failing with s HTTP 404 error during service account impersonation. The issue was caused by:
Missing project ID resolution (notice the `-` in `projects/-/serviceAccounts/...`)
The service account impersonation was failing during the first authentication attempt.
The action would eventually succeed via its fallback mechanism, making the job successful, but caused confusing error logs. To prevent it, I replaced the failing `login-to-gar` action with Direct Workload Identity Federation using `google-github-actions/auth` (https://github.com/grafana/deployment_tools/tree/ece2dc51a27a36d68bc75543f1e40f6e2d78667c/terraform/projects/grafanalabs-workload-identity#using-google-github-actionsauth-direc …

GHA: a few improvements

---

src/components/CheckForm/AlertsPerCheck/AlertsPerCheck.tsx

Closes https://github.com/grafana/synthetic-monitoring/issues/316
Adds a link to notification polices so users can configure where their alerts will be routed.

Per-check alerts: add link to notification policies

---

src/page/AlertingPage.tsx
src/page/pageDefinitions.ts
src/plugin.json
src/routing/InitialisedRouter.test.tsx

Closes https://github.com/grafana/synthetic-monitoring/issues/317
The "Alerts" menu item takes users to the legacy alerts page, which could cause confusion since the new per-check alerting system isn't represented there. Users might expect to see their current alerts but only find legacy ones with no clear indication of where to find the new alerts.
- Renamed menu item from "Alerts" to "Alerts (Legacy)" for clarity
- Added prominent info alert at the top of the page explaining this page shows legacy alerts using the alert sensitivity system 
- Recommends using the new per-check alerts system instead
- Explains where to configure per-check alerts (in the "Alerting" section when creating/editing checks)
- Updated documentation link to point to per-check alerts documentation

fix: add information about legacy vs per-check alerts in Alerting page

---

src/components/CheckTestResultsModal.tsx
src/faro.ts
src/scenes/debugTransform.ts
src/test/handlers/index.ts
src/test/silenceErrors.ts

Fixing the lint warnings that are generated since we added back allowing `console.log` (as for production they are stripped out).

fix: lint warnings

---

src/scenes/Common/alertAnnotations.ts
src/scenes/HTTP/HttpDashboard.tsx

Closes https://github.com/grafana/synthetic-monitoring-app/issues/1132
Since the alerting team has added the new `GRAFANA_ALERTS` metric to obtain the `alertstatus` of the alerts, we can now use it to display annotations. I've included it to the current `firing`/`pending` annotations in the checks dashboards. 
**Note:** As of today, this metric is only available in prod for _free_ users (see https://github.com/grafana/alerting-squad/issues/1024) but its absence does now cause any issue with current annotations as the queries check for `ALERTS or GRAFANA_ALERTS`
I have tested these annotations using a free account with a custom dashboard and it shows as expected:

feat: add GRAFANA_ALERTS to annotations for firing/pending alerts

---

src/scenes/HTTP/ErrorRateMap.tsx

The ErrorRateMap component sometimes throws this error on first load, as reported in [Slack](https://raintank-corp.slack.com/archives/C0162C1K9E1/p1752663586695719):
```
TypeError: Cannot read properties of undefined (reading 'setActive')
at GeomapPanel.tsx:367:25
// at this.mouseWheelZoom!.setActive(Boolean(options.mouseWheelZoom));
```
This typically happens on the first page load and goes away after refresh.
The issue is a race condition where the geomap panel tries to initialize before the data queries complete and the expected data structure is available. The geomap attempts to call `setActive()` on undefined objects during its internal initialization.
1. **Loading state tracking** - Added `hasLoaded` state variable to track if data has loaded successfully at least once
2. **Prevent …

fix: prevent loading errorRateMap when data has not finished loading

---

.github/workflows/call_deploy-plugin.yml
src/components/ProbeSetupModal/ProbeSetupModal.tsx

The Github action to release to staging (ops) needed some parenthesis so it passed the correct value along. [Log with error.](https://github.com/grafana/synthetic-monitoring-app/actions/runs/16565122685/job/46843271217)
Also brought along the lint error fix that made it to `main`.

fix: github actions staging value passthrough

---

.github/workflows/call_validate-terraform.yml
scripts/terraform-validation/generate-test-configs.ts
src/test/fixtures/checks.ts

Changes the CI Terraform Validation job to run with the latest terraform provider version.  
Also modifies the GHA logs to be more explicit about errors in failures, and display the terraform provider version used.
Failure from https://github.com/grafana/synthetic-monitoring-app/actions/runs/16815040949/job/47629666992?pr=1220
Success from https://github.com/grafana/synthetic-monitoring-app/actions/runs/16815086056/job/47629821209?pr=1220

fix: always use latest terraform provider version for validation check

---

src/checkUsageCalc.test.ts
src/checkUsageCalc.ts

There was a discrepancy between the frontend and backend calculations for determining the total number of probe executions within an alert period for "failed executions" alerts. This caused the backend to reject valid alerts that the frontend incorrectly showed as acceptable.
- Check frequency: 6 minutes
- Alert period: 10 minutes  
- Number of probes: 1
- **Frontend showed**: 2 executions (incorrect)
- **Backend calculated**: 1 execution (correct)
- **Result**: Backend rejected the alert when threshold was set to 2/2
The frontend was using `Math.round()` which could round up fractional executions.
Backend implementation: https://github.com/grafana/synthetic-monitoring-api/blob/410d4c402829df22f3d6adf4d00fa0146ebe01ad/internal/alerts/rules.go#L235-L239

fix: make totalChecksPerPeriod calculation equal to backend

---

src/data/permissions.ts
src/data/useSecrets.ts
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretCard.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretsManagementTab.test.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretsManagementTab.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretsManagementUI.test.tsx
src/page/ConfigPageLayout/tabs/SecretsManagementTab/SecretsManagementUI.tsx
src/plugin.json
src/test/fixtures/rbacPermissions.ts
src/test/utils.ts
src/types.ts

Implements granular restrictions on the secrets UI consuming the following fixed permissions:
```
'secret.securevalues:create',
'secret.securevalues:read'
'secret.securevalues:write'
'secret.securevalues:delete'
```
**Editor with no secrets permissions assigned:**
**Editor with read permissions assigned:**
- with no secrets
- with secrets
**Editor with read+create permissions assigned:**
- with no secrets
- with secrets
**Editor with read+update permissions assigned:**
**Editor with read+delete permissions assigned:**
**Editor with read+create+update+delete permissions assigned:**

feat: apply granular secrets permissions

---

src/data/probeAPIServerMappings.json

Switzerland was recently added as a new region and the app is lacking the hard-coded mapping: https://grafana.com/docs/grafana-cloud/testing/synthetic-monitoring/set-up/set-up-private-probes/#add-a-new-probe-in-your-grafana-instance
Ran the script to update the mapping 😄

fix: update probe mappings

---

.github/workflows/call_dangerJS.yml

DangerJS has been reporting inaccurate bundle size changes for recent PRs (see https://raintank-corp.slack.com/archives/C098DB0038C/p1756367397330709). 
The issue was that the `currentBundleSize` artifact download was using `dawidd6/action-download-artifact` without proper parameters, causing it to download artifacts from the most recent successfully completed workflow run instead of the current PR's build. However, since the `currentBundleSize` artifact is generated within the same workflow run as DangerJS (both are part of on-pr-creation.yml), the correct solution is to use `actions/download-artifact` which downloads from the current workflow run.
The fix changes the `currentBundleSize` download to use `actions/download-artifact` instead of `dawidd6/action-download-artifact`, ensuring …

fix: correct danger js PR stats

---

src/scenes/components/TimepointExplorer/TimepointExplorer.context.tsx
src/scenes/components/TimepointExplorer/XAxis.tsx
src/scenes/components/TimepointExplorer/XAxis.utils.test.ts
src/scenes/components/TimepointExplorer/XAxis.utils.ts

When the `renderingStrategy` is `start` the xaxis is rendering incorrectly -- the time values are displaying from latest to oldest.
There is also a problem where the check creation is being rounded using `Math.round` and not `Math.ceil` like all the other event updates now.
1. Change the xaxis indices depending on the `renderingStrategy`.
2. Use `Math.ceil` instead of `Math.round` for check creation.

fix: Timepoint Explorer xaxis and check creation rounding

---

src/data/probeAPIServerMappings.json

Fixes Probe API Server Mappings as flagged by https://github.com/grafana/synthetic-monitoring-app/pull/1269#issuecomment-3325321510

fix: probe api mappings

---

src/components/Clipboard/CopyToClipboard.tsx
yarn.lock

Fixes the Grafana API compatibility check failure by upgrading Grafana dependencies to their latest compatible versions.
The levitate compatibility check was failing because:
- Local dependencies were locked to `12.1.0` in yarn.lock
- The compatibility check tests against latest versions (`12.2.0`)
- Found 2 incompatibilities in `@grafana/runtime` between versions 12.1.0 → 12.2.0
- Created a mismatch between what we're developing against vs. what we're testing compatibility with
Upgraded Grafana dependencies from 12.1.0 to 12.2.0:
- `@grafana/data`: `12.1.0` → `12.2.0`
- `@grafana/runtime`: `12.1.0` → `12.2.0` 
- `@grafana/schema`: `12.1.0` → `12.2.0`
- `@grafana/ui`: `12.1.0` → `12.2.0`

fix: upgrade Grafana dependencies to resolve API compatibility check

---

src/data/useGMAlerts.test.ts
src/data/useGMAlerts.ts

Resolves a bug where the UI was displaying the wrong alert rule group for period-based alerts. The issue occurred because `findGroupWithMatchingRule` used substring matching (`includes()`), causing situations like `ProbeFailedExecutionsTooHigh [5m]` to incorrectly match `ProbeFailedExecutionsTooHigh [10m]` when the `10m` group appeared first in the array, as it was matching by rule name.
The fix replaces substring matching with exact rule name matching by constructing the full rule name including the period (e.g., `ProbeFailedExecutionsTooHigh [5m]`). This ensures the UI displays the correct alert group that matches the check's configured period.
Fixes https://github.com/grafana/support-escalations/issues/18565
**Before**
https://github.com/user-attachments/assets/587422ef-c91a-49cb-971e-6 …

fix: resolve incorrect alert rule group matching
